import '../styles/banco.css';
import { h, empty } from '../utils/helpers.js';
import { supabaseConfigured, dbSelect } from '../core/supabase.js';

interface StatRow { readonly key: string; readonly count: number; }
function isRecord(value: unknown): value is Readonly<Record<string, unknown>> { return typeof value === 'object' && value !== null; }
function asStatRows(value: unknown): readonly StatRow[] { if (!Array.isArray(value)) return []; return value.flatMap((row): StatRow[] => { if (!isRecord(row) || typeof row.key !== 'string') return []; const count = typeof row.count === 'number' ? row.count : Number(row.count); return [{ key: row.key, count: Number.isFinite(count) ? count : 0 }]; }); }
function asRows(value: unknown): readonly Readonly<Record<string, unknown>>[] { return Array.isArray(value) ? value.filter(isRecord) : []; }
function fmt(value: number): string { return Number(value || 0).toLocaleString('pt-BR'); }
function tile(icon: string, valueElement: HTMLDivElement, label: string, emphasized = false): HTMLDivElement { return h('div', { className: `banco-tile${emphasized ? ' banco-tile--mag' : ''}` }, h('div', { className: 'banco-tile__icon' }, icon), valueElement, h('div', { className: 'banco-tile__label' }, label)); }
export function bancoPage(): HTMLDivElement {
  const page = h('div', { className: 'page-banco' });
  page.appendChild(h('div', { className: 'page-header anim-fade-in', style: { marginBottom: '12px' } }, h('div', { className: 'page-header__crumbs' }, h('span', null, 'BALUARTE'), h('span', null, '›'), h('span', null, 'BANCO')), h('h1', { className: 'page-header__title' }, '🗄️ Painel do Banco'), h('p', { className: 'page-header__description' }, 'Números ', h('span', { className: 'u-text-cyan' }, 'ao vivo'), ' do banco oficial (Supabase). Leitura pública protegida por ', h('span', { className: 'u-mono' }, 'RLS'), ' — escrita anônima só por funções seguras.')));
  const visitsValue = h('div', { className: 'banco-tile__value' }, '…'); const viewsValue = h('div', { className: 'banco-tile__value' }, '…'); const pagesValue = h('div', { className: 'banco-tile__value' }, '…'); const muralValue = h('div', { className: 'banco-tile__value' }, '…');
  page.appendChild(h('div', { className: 'banco-grid' }, tile('👁', visitsValue, 'Visitas'), tile('📊', viewsValue, 'Páginas vistas'), tile('🧭', pagesValue, 'Páginas distintas'), tile('📣', muralValue, 'Posts no mural', true)));
  page.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, '🔝 Top páginas')));
  const topWrap = h('div', { className: 'banco-top' }, h('p', { className: 'u-text-muted', style: { fontSize: '13px' } }, 'Carregando…')); page.appendChild(topWrap);
  page.appendChild(h('p', { className: 'u-text-muted banco-foot', style: { fontSize: '12px', marginTop: 'var(--space-md)' } }, '🗂️ Tabelas: ', h('span', { className: 'u-mono' }, 'mural_posts'), ', ', h('span', { className: 'u-mono' }, 'site_stats'), ' · RLS ligado · escrita anônima só via ', h('span', { className: 'u-mono' }, 'bump_visits'), ' / ', h('span', { className: 'u-mono' }, 'bump_view'), '. Detalhes em ', h('span', { className: 'u-mono' }, 'docs/SUPABASE.md'), '.'));
  function fail(message: string): void { [visitsValue, viewsValue, pagesValue, muralValue].forEach((element) => { element.textContent = '—'; }); empty(topWrap); topWrap.appendChild(h('p', { className: 'u-text-muted', style: { fontSize: '13px' } }, message)); }
  if (!supabaseConfigured()) { fail('Banco não configurado neste ambiente.'); return page; }
  (async (): Promise<void> => { try { const stats = asStatRows(await dbSelect('site_stats', 'select=key,count&order=count.desc')); if (!stats.length) throw new Error('sem dados'); const visits = stats.find((row) => row.key === 'visits'); const views = stats.filter((row) => row.key.startsWith('view:')).map((row) => ({ route: row.key.replace(/^view:/, ''), count: row.count })); const totalViews = views.reduce((sum, row) => sum + row.count, 0); visitsValue.textContent = fmt(visits?.count ?? 0); viewsValue.textContent = fmt(totalViews); pagesValue.textContent = fmt(views.length); empty(topWrap); if (!views.length) { topWrap.appendChild(h('p', { className: 'u-text-muted', style: { fontSize: '13px' } }, 'Ainda sem views registradas — navegue pelo site que elas aparecem aqui.')); } else { const max = views[0]?.count || 1; views.slice(0, 10).forEach((view) => topWrap.appendChild(h('div', { className: 'banco-bar' }, h('span', { className: 'banco-bar__route u-mono' }, view.route), h('span', { className: 'banco-bar__track' }, h('span', { className: 'banco-bar__fill', style: { width: `${Math.max(4, (view.count / max) * 100)}%` } })), h('span', { className: 'banco-bar__n u-mono' }, fmt(view.count))))); } } catch { fail('Banco indisponível agora (offline ou migrations ainda não aplicadas).'); return; } try { const posts = asRows(await dbSelect('mural_posts', 'select=id')); muralValue.textContent = fmt(posts.length); } catch { muralValue.textContent = '—'; } })();
  return page;
}
