import '../styles/diagnostico.css';
import { h } from '../utils/helpers.js';
import { bus } from '../core/events.js';
import { VERSION } from '../data/version.js';
import { estadoPolitica } from '../core/politica.js';
import { conceder, revogar, ultimasDecisoes } from '../core/permissions.js';
import type { PermissionView, PolicyState } from '../core/politica.js';
import type { ResolvedFlag } from '../core/flags.js';
import type { StorageSchemaState } from '../core/storage.js';
import { definir as definirFlag, resetar as resetarFlag } from '../core/flags.js';
import { storage } from '../core/storage.js';

interface ProbeResult { readonly nome: string; readonly ok: boolean; }
const SONDAS: readonly (readonly [string, () => boolean])[] = [
  ['localStorage', () => storage.hasLocalStorage],
  ['IndexedDB', () => typeof indexedDB !== 'undefined'],
  ['Service Worker', () => 'serviceWorker' in navigator],
  ['WebGL', () => { const canvas = document.createElement('canvas'); return Boolean(canvas.getContext('webgl2') || canvas.getContext('webgl')); }],
  ['WebGPU', () => 'gpu' in navigator],
  ['Web Audio', () => typeof AudioContext !== 'undefined' || 'webkitAudioContext' in globalThis],
  ['Web Worker', () => typeof Worker !== 'undefined'],
  ['Crypto subtle', () => Boolean(globalThis.crypto?.subtle)],
  ['Ponte do Launcher', () => window.baluarte?.native === true],
];
function sondar(): readonly ProbeResult[] { return SONDAS.map(([nome, probe]) => { let ok = false; try { ok = probe(); } catch { ok = false; } return { nome, ok }; }); }
function selo(texto: string, tipo: string): HTMLSpanElement { return h('span', { className: `diag-selo diag-selo--${tipo}` }, texto); }
function secao(titulo: string, subtitulo: string, ...conteudo: Array<HTMLElement | null>): HTMLElement { return h('section', { className: 'diag-secao' }, h('h2', { className: 'diag-secao__titulo' }, titulo), subtitulo ? h('p', { className: 'diag-secao__sub' }, subtitulo) : null, ...conteudo); }
function linhaSonda(probe: ProbeResult): HTMLLIElement { return h('li', { className: 'diag-sonda' }, h('span', { className: 'diag-sonda__nome' }, probe.nome), selo(probe.ok ? '✓ disponível' : '— ausente', probe.ok ? 'ok' : 'off')); }
function linhaPermissao(permission: PermissionView, redraw: () => void): HTMLLIElement { const restricted = permission.risco === 'restrito'; return h('li', { className: 'diag-item' }, h('div', { className: 'diag-item__cabeca' }, h('code', { className: 'diag-item__id' }, permission.id), selo(permission.risco, restricted ? 'risco' : 'neutro')), permission.descricao ? h('p', { className: 'diag-item__desc' }, permission.descricao) : null, h('div', { className: 'diag-item__acao' }, selo(permission.concedida ? '● concedida' : '○ negada', permission.concedida ? 'ok' : 'off'), h('button', { className: 'diag-btn', type: 'button', onclick: (): void => { if (permission.concedida) revogar(permission.id, { origem: 'diagnostico' }); else conceder(permission.id, { origem: 'diagnostico' }); redraw(); } }, permission.concedida ? 'Revogar' : 'Conceder'))); }
function linhaFlag(flag: ResolvedFlag, environment: 'web' | 'app', redraw: () => void): HTMLLIElement { const outside = flag.ambiente !== 'ambos' && flag.ambiente !== environment; return h('li', { className: 'diag-item' }, h('div', { className: 'diag-item__cabeca' }, h('code', { className: 'diag-item__id' }, flag.id), selo(flag.nivel, flag.nivel === 'estavel' ? 'ok' : flag.nivel === 'beta' ? 'neutro' : 'risco'), flag.ambiente !== 'ambos' ? selo(`só ${flag.ambiente}`, 'neutro') : null), flag.descricao ? h('p', { className: 'diag-item__desc' }, flag.descricao) : null, h('div', { className: 'diag-item__acao' }, selo(flag.ativo ? '● ligada' : '○ desligada', flag.ativo ? 'ok' : 'off'), outside ? h('span', { className: 'diag-item__nota' }, flag.ambiente === 'app' ? 'Só funciona dentro do Baluarte Launcher.' : 'Só funciona no navegador.') : h('button', { className: 'diag-btn', type: 'button', onclick: (): void => { definirFlag(flag.id, !flag.ativo); redraw(); } }, flag.ativo ? 'Desligar' : 'Ligar'), flag.escolhida && !outside ? h('button', { className: 'diag-btn diag-btn--fraco', type: 'button', onclick: (): void => { resetarFlag(flag.id); redraw(); } }, 'Padrão') : null)); }
function linhaEsquema(schema: StorageSchemaState): HTMLLIElement { const stale = schema.gravada !== null && schema.gravada !== schema.versao; return h('li', { className: 'diag-item diag-item--compacto' }, h('div', { className: 'diag-item__cabeca' }, h('code', { className: 'diag-item__id' }, schema.chave), selo(schema.classe, schema.classe === 'sensivel' || schema.classe === 'secreto' ? 'risco' : 'neutro')), h('p', { className: 'diag-item__desc' }, `esquema v${schema.versao} · gravado: ${schema.gravada === null ? 'nada ainda' : `v${schema.gravada}`}${schema.temMigracao ? ' · tem migração' : ' · sem migração'}`), stale ? selo('⚠ divergente', 'risco') : null); }
function recordText(value: unknown, key: string): string { if (typeof value !== 'object' || value === null || !(key in value)) return ''; const field = (value as Record<string, unknown>)[key]; return typeof field === 'string' ? field : ''; }
function permissionLogSection(redraw: () => void): HTMLElement { const decisions = ultimasDecisoes(15); if (!decisions.length) return secao('Últimas decisões de permissão', 'Rastro em memória (não persiste). Serve para responder "por que isso foi negado?".', h('p', { className: 'diag-vazio' }, 'Nada registrado nesta sessão.')); const list = decisions.slice().reverse().map((decision) => { const action = recordText(decision, 'acao'); const id = recordText(decision, 'id'); const rawIds = typeof decision === 'object' && decision !== null ? (decision as Record<string, unknown>).ids : undefined; const ids = Array.isArray(rawIds) ? rawIds.filter((value): value is string => typeof value === 'string').join(', ') : ''; const result = recordText(decision, 'resultado'); return h('li', { className: 'diag-log__linha' }, h('code', null, action), h('span', null, id || ids), result ? selo(result, result === 'ok' ? 'ok' : 'risco') : null); }); return secao('Últimas decisões de permissão', 'Rastro em memória (não persiste). Serve para responder "por que isso foi negado?".', h('ul', { className: 'diag-log' }, ...list)); }
function renderPolicy(root: HTMLDivElement, policy: PolicyState, redraw: () => void): void { const probes = sondar(); const denied = policy.permissoes.declaradas.filter((permission) => !permission.concedida); const environment = policy.ambiente; const hero = h('header', { className: 'diag-hero' }, h('h1', { className: 'diag-hero__titulo' }, 'Diagnóstico do sistema'), h('p', { className: 'diag-hero__sub' }, `Baluarte v${VERSION} · ambiente: ${environment === 'app' ? 'Launcher (app)' : 'navegador (web)'}`), h('div', { className: 'diag-hero__resumo' }, selo(`${policy.permissoes.concedidas.length} de ${policy.permissoes.declaradas.length} permissões`, 'neutro'), selo(`${policy.porNivel.estavel.length} estáveis`, 'ok'), selo(`${policy.porNivel.beta.length} beta`, 'neutro'), selo(`${policy.porNivel.experimental.length} experimentais`, 'risco'), selo(`${bus.contarOuvintes('route:change')} ouvintes em route:change`, 'neutro'))); const environmentSection = secao('Ambiente', 'O que este navegador oferece.', h('ul', { className: 'diag-sondas' }, ...probes.map(linhaSonda))); const stabilitySection = secao('Estabilidade', 'O que a 1.0.0 promete. "Estável" significa previsível, testado, recuperável e seguro — o resto está declarado como tal de propósito.', h('ul', { className: 'diag-lista' }, ...policy.flags.map((flag) => linhaFlag(flag, environment, redraw)))); const permissionsSection = secao('Permissões', denied.length ? `${denied.length} negada(s). Ferramenta do JARVIS que responder 🔒 precisa da permissão correspondente ligada aqui.` : 'Tudo concedido. Risco "restrito" nunca entra por curinga — só pelo botão, um a um.', h('ul', { className: 'diag-lista' }, ...policy.permissoes.declaradas.map((permission) => linhaPermissao(permission, redraw)))); const dataSection = secao('Dados guardados', 'Cada chave com esquema declarado tem versão e classificação. "Divergente" quer dizer que o gravado não é o que este código entende.', h('ul', { className: 'diag-lista' }, ...policy.esquemas.map(linhaEsquema))); root.replaceChildren(hero, environmentSection, stabilitySection, permissionsSection, dataSection, permissionLogSection(redraw)); }
export function diagnosticoPage(): HTMLDivElement { const root = h('div', { className: 'diag' }); const redraw = (): void => renderPolicy(root, estadoPolitica(), redraw); redraw(); return root; }
