import { h, cx, empty, debounce } from '../utils/helpers.js';
import { storage } from '../core/storage.js';
import { toast } from '../utils/toast.js';
import { fetchCurrencies, fetchCrypto, fmtBRL, fmtUSD, fmtPct, CURRENCY_PAIRS } from '../utils/economia-api.js';
import type { CurrencyQuote, CryptoQuote } from '../utils/economia-api.js';

const STORAGE_KEY = 'economia:cache';
let currencyGridEl: HTMLDivElement | null = null;
let cryptoGridEl: HTMLDivElement | null = null;
let statusEl: HTMLSpanElement | null = null;
let converterEl: HTMLDivElement | null = null;
let lastCurrencies: readonly CurrencyQuote[] = [];
function trendClass(value: number | null | undefined): string { return value == null ? 'u-text-muted' : value >= 0 ? 'u-text-success' : 'u-text-danger'; }
function trendArrow(value: number | null | undefined): string { return value == null ? '·' : value >= 0 ? '▲' : '▼'; }
function renderCurrencies(list: readonly CurrencyQuote[]): void { if (!currencyGridEl) return; empty(currencyGridEl); list.forEach((currency) => currencyGridEl?.appendChild(h('div', { className: 'eco-card' }, h('div', { className: 'eco-card__head' }, h('span', { className: 'eco-card__icon' }, currency.icon), h('span', { className: 'eco-card__code u-mono' }, currency.code)), h('div', { className: 'eco-card__label' }, currency.label), h('div', { className: 'eco-card__value' }, currency.error ? '— erro —' : fmtBRL(currency.bid)), h('div', { className: cx('eco-card__pct', trendClass(currency.pct)) }, trendArrow(currency.pct), ' ', fmtPct(currency.pct)), !currency.error && currency.high != null ? h('div', { className: 'eco-card__range u-text-muted u-mono' }, `H ${fmtBRL(currency.high)} · L ${fmtBRL(currency.low)}`) : null))); }
function renderCrypto(list: readonly CryptoQuote[]): void { if (!cryptoGridEl) return; empty(cryptoGridEl); list.forEach((crypto) => cryptoGridEl?.appendChild(h('div', { className: 'eco-card eco-card--crypto' }, h('div', { className: 'eco-card__head' }, h('span', { className: 'eco-card__icon' }, '◈'), h('span', { className: 'eco-card__code u-mono' }, crypto.symbol)), h('div', { className: 'eco-card__label' }, crypto.label), h('div', { className: 'eco-card__value' }, crypto.error ? '— erro —' : fmtBRL(crypto.brl)), h('div', { className: 'eco-card__usd u-text-muted u-mono' }, crypto.error ? '' : fmtUSD(crypto.usd)), h('div', { className: cx('eco-card__pct', trendClass(crypto.pct24h)) }, trendArrow(crypto.pct24h), ' ', fmtPct(crypto.pct24h), ' (24h)')))); }
function renderConverter(): void { if (!converterEl) return; empty(converterEl); if (!lastCurrencies.length) { converterEl.appendChild(h('div', { className: 'u-text-muted', style: { fontSize: '12px' } }, 'Atualize as cotações para usar o conversor.')); return; } const amountInput = h('input', { className: 'input', type: 'number', value: '100', step: 'any' }); const fromSelect = h('select', { className: 'input' }, h('option', { value: 'BRL' }, 'Real (BRL)'), ...lastCurrencies.filter((currency) => !currency.error).map((currency) => h('option', { value: currency.code }, currency.label))); const toSelect = h('select', { className: 'input' }, h('option', { value: 'BRL', selected: true }, 'Real (BRL)'), ...lastCurrencies.filter((currency) => !currency.error).map((currency) => h('option', { value: currency.code }, currency.label))); const resultEl = h('div', { className: 'eco-conv__result u-mono' }, '—'); const rateToBrl = (code: string): number | null => { if (code === 'BRL') return 1; return lastCurrencies.find((currency) => currency.code === code)?.bid ?? null; }; const calculate = (): void => { const amount = Number.parseFloat(amountInput.value) || 0; const fromRate = rateToBrl(fromSelect.value); const toRate = rateToBrl(toSelect.value); if (fromRate == null || toRate == null) { resultEl.textContent = '—'; return; } resultEl.textContent = new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 6 }).format((amount * fromRate) / toRate); }; amountInput.addEventListener('input', debounce(calculate, 120)); fromSelect.addEventListener('change', calculate); toSelect.addEventListener('change', calculate); converterEl.appendChild(h('div', { className: 'eco-conv' }, h('label', null, h('span', null, 'VALOR'), amountInput), h('label', null, h('span', null, 'DE'), fromSelect), h('label', null, h('span', null, 'PARA'), toSelect), h('div', { className: 'eco-conv__out' }, h('span', { className: 'u-text-muted', style: { fontSize: '10px' } }, 'RESULTADO'), resultEl))); calculate(); }
function errorMessage(reason: unknown): string { return reason instanceof Error ? reason.message : 'falha desconhecida'; }
async function refresh(): Promise<void> { if (statusEl) { statusEl.textContent = 'Atualizando…'; statusEl.className = 'badge badge--warning'; } try { const [currencies, crypto] = await Promise.allSettled([fetchCurrencies(), fetchCrypto()]); if (currencies.status === 'fulfilled') { lastCurrencies = currencies.value; renderCurrencies(currencies.value); } else if (currencyGridEl) { empty(currencyGridEl); currencyGridEl.appendChild(h('div', { className: 'eco-error u-text-danger' }, `⚠ Falha ao carregar câmbio: ${errorMessage(currencies.reason)}`)); } if (crypto.status === 'fulfilled') renderCrypto(crypto.value); else if (cryptoGridEl) { empty(cryptoGridEl); cryptoGridEl.appendChild(h('div', { className: 'eco-error u-text-danger' }, `⚠ Falha ao carregar cripto: ${errorMessage(crypto.reason)}`)); } renderConverter(); const ok = currencies.status === 'fulfilled' || crypto.status === 'fulfilled'; if (statusEl) { statusEl.textContent = ok ? `● ${new Date().toLocaleTimeString('pt-BR')}` : 'OFFLINE'; statusEl.className = ok ? 'badge badge--success' : 'badge badge--danger'; } if (ok) { storage.set(STORAGE_KEY, { currencies: lastCurrencies, ts: Date.now() }); toast('Cotações atualizadas', { type: 'success', duration: 1500 }); } } catch (error: unknown) { if (statusEl) { statusEl.textContent = 'ERRO'; statusEl.className = 'badge badge--danger'; } toast(`Erro: ${errorMessage(error)}`, { type: 'danger' }); } }
export function economiaPage(): HTMLDivElement { const fullPage = h('div', { className: 'page-economia' }); statusEl = h('span', { className: 'badge badge--muted' }, 'NÃO CARREGADO'); fullPage.appendChild(h('div', { className: 'page-header anim-fade-in', style: { marginBottom: '12px' } }, h('div', { className: 'page-header__crumbs' }, h('span', null, 'BALUARTE'), h('span', null, '›'), h('span', null, 'ECONOMIA')), h('h1', { className: 'page-header__title' }, '◈ Economia'), h('p', { className: 'page-header__description' }, 'Cotações live de ', h('span', { className: 'u-text-cyan' }, 'câmbio'), ' (AwesomeAPI) e ', h('span', { className: 'u-text-cyan' }, 'criptomoedas'), ' (CoinGecko). Requer conexão. Inclui conversor rápido.'))); fullPage.appendChild(h('div', { className: 'eco-toolbar' }, h('button', { className: 'btn btn--primary', onclick: (): void => { void refresh(); } }, '↻ Atualizar cotações'), statusEl)); fullPage.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, 'Câmbio'), h('span', { className: 'section-header__count' }, `${CURRENCY_PAIRS.length} pares`))); currencyGridEl = h('div', { className: 'eco-grid' }); fullPage.appendChild(currencyGridEl); fullPage.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, 'Conversor'))); converterEl = h('div', { className: 'eco-converter-wrap' }); fullPage.appendChild(converterEl); fullPage.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, 'Criptomoedas'))); cryptoGridEl = h('div', { className: 'eco-grid' }); fullPage.appendChild(cryptoGridEl); [currencyGridEl, cryptoGridEl].forEach((grid) => grid?.appendChild(h('div', { className: 'u-text-muted', style: { padding: '16px' } }, 'Clique em "Atualizar cotações" para carregar.'))); renderConverter(); window.setTimeout(() => { void refresh(); }, 100); return fullPage; }
