import '../styles/nucleo-screen.css';
import { h, empty } from '../utils/helpers.js';
import { bus } from '../core/events.js';
import { loadConfig, saveConfig, processLocal, processClaude, processOllama, processServer, processHermes, processClaudeServer, processOpenClaw, processAgent, getBaluarteBriefing } from '../utils/jarvis-engine.js';
import type { JarvisConfig, JarvisMessage, JarvisToolCallback } from '../utils/jarvis-engine.js';
import { getStatusText } from '../utils/baluarte-status.js';
import { processHermesAgent } from '../utils/jarvis-hermes-agent.js';
import { processHermesLocal, healthHermesLocal, listHermesLocalModels, HERMES_LOCAL_PRESETS } from '../utils/hermes-local.js';
import { nativeHermesStatus } from '../utils/jarvis-hermes-native.js';
import type { NativeHermesStatus } from '../utils/jarvis-hermes-native.js';
import { WEBLLM_MODELS } from '../utils/jarvis-webllm.js';
import { speak, stopSpeaking, voiceEnabled, setVoiceEnabled, voiceLang, setVoiceLang, setElevenKey, hasElevenKey, VOICE_LANGS } from '../utils/jarvis-voice.js';
import { initNucleoLink, getNucleoUrl, setNucleoUrl, setNucleoToken, simulateNucleoEvent } from '../utils/nucleo-socket.js';
import type { NucleoEvent, NucleoStatus } from '../utils/nucleo-socket.js';
import { mountNucleoScene } from '../utils/nucleo-scene.js';
import type { NucleoSceneController } from '../utils/nucleo-scene.js';
import { initArquivosTools, statusArquivos, buscarArquivos, relatorioArquivos, lerArquivo, analisarPasta, grepArquivos, moverArquivo, apagarArquivo, verLixeira, restaurarArquivo, sentinelaPC } from '../utils/jarvis-arquivos.js';

const PULSE_MS: Readonly<Record<'command' | 'biometric' | 'telemetry' | 'system' | 'voice', number>> = { command: 420, biometric: 300, telemetry: 200, system: 160, voice: 360 };
const MODOS = ['local', 'webllm', 'hermes-agente', 'hermes-local', 'claude', 'ollama', 'servidor', 'hermes', 'claude-servidor', 'openclaw', 'agente'] as const;
type Modo = (typeof MODOS)[number];
type VitalId = 'nucleo' | 'rede' | 'eventos' | 'energia' | 'remoto' | 'bio' | 'modo' | 'motor';
type VitalTone = 'ok' | 'warn';
type PanelFunction = { readonly id: string; readonly nome: string; readonly match: RegExp; readonly load: () => Promise<HTMLElement> };
interface NucleoArgs { readonly tab?: unknown; readonly query?: Record<string, unknown> }
interface PendingAction { executar(): Promise<string> }
interface BatteryManagerLike extends EventTarget { level: number; charging: boolean }

function isRecord(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === 'object' && !Array.isArray(value); }
function textOf(value: unknown, fallback = ''): string { return typeof value === 'string' ? value : fallback; }
function numberOf(value: unknown): number | null { return typeof value === 'number' && Number.isFinite(value) ? value : null; }
function errorText(error: unknown): string { return error instanceof Error ? error.message : 'erro desconhecido'; }
function isModo(value: string): value is Modo { return (MODOS as readonly string[]).includes(value); }

const FUNCOES: readonly PanelFunction[] = [
  { id: 'grafo', nome: 'Grafo de Código', match: /\bgrafo\b|c[óo]digo (3d|em 3d)/, load: () => import('./git-nexus.js').then((module) => module.gitNexusPage()) },
  { id: 'vision', nome: 'Corpo Total', match: /corpo (total|inteiro)|ativa\w* (a )?vis[ãa]o|\bvis[ãa]o\b/, load: () => import('./jarvis-vision.js').then((module) => module.jarvisVisionPage()) },
  { id: 'gerar', nome: 'Gerar Código', match: /gerar c[óo]digo|gera c[óo]digo/, load: () => import('./gerar-codigo.js').then((module) => module.gerarCodigoPage()) },
  { id: 'conselho', nome: 'Conselho de IAs', match: /conselho/, load: () => import('./conselho.js').then((module) => module.conselhoPage()) },
  { id: 'apis', nome: 'Central de APIs', match: /\bapis?\b|central de apis|chaves/, load: () => import('./apis.js').then((module) => module.apisPage()) },
  { id: 'dashboard', nome: 'Dashboard', match: /dashboard|painel de (m[ée]tricas|status)/, load: () => import('./jarvis-dashboard.js').then((module) => module.jarvisDashboardPage()) },
  { id: 'ml', nome: 'ML da Memória', match: /\bml\b|aprendizado|machine learning/, load: () => import('./aprendizado.js').then((module) => module.aprendizadoPage()) },
  { id: 'llm', nome: 'Mini-LLM', match: /mini[- ]?llm|\bllm\b/, load: () => import('./llm-lab.js').then((module) => module.llmLabPage()) },
  { id: 'cerebro', nome: 'Segundo Cérebro', match: /c[ée]rebro/, load: () => import('./cerebro.js').then((module) => module.cerebroPage()) },
  { id: 'memoria', nome: 'Memória', match: /mem[óo]ria/, load: () => import('./memoria.js').then((module) => module.memoriaPage()) },
  { id: 'terminal', nome: 'Terminal-IA', match: /terminal/, load: () => import('./terminal-ia.js').then((module) => module.terminalIaPage()) },
  { id: 'seguranca', nome: 'Segurança', match: /seguran[çc]a/, load: () => import('./seguranca.js').then((module) => module.segurancaPage()) },
  { id: 'ia', nome: 'IA Proprietária', match: /ia propriet[áa]ria|propriet[áa]ria/, load: () => import('./ia-proprietaria.js').then((module) => module.iaProprietariaPage()) },
  { id: 'jarvis', nome: 'J.A.R.V.I.S. completo', match: /jarvis completo|chat completo|sess[õo]es/, load: () => import('./jarvis.js').then((module) => module.jarvisPage()) },
];

function payloadRecord(value: unknown): Record<string, unknown> { return isRecord(value) ? value : {}; }

export function gitNexusNucleo(args: NucleoArgs = {}): HTMLDivElement {
  const page = h('div', { className: 'nucleo-screen' });
  const sceneEl = h('div', { className: 'nucleo-screen__scene', 'aria-hidden': 'true' }); page.appendChild(sceneEl);
  let scene: NucleoSceneController | null = null;

  const vitals: Partial<Record<VitalId, HTMLSpanElement>> = {};
  function vitalRow(id: VitalId, label: string, initial: string): HTMLDivElement { const value = h('span', { className: 'nucleo-vitals__val' }, initial); vitals[id] = value; return h('div', { className: 'nucleo-vitals__row' }, h('span', { className: 'nucleo-vitals__label' }, label), value); }
  function setVital(id: VitalId, text: string, tone?: VitalTone): void { const element = vitals[id]; if (!element) return; element.textContent = text; element.className = `nucleo-vitals__val${tone ? ` nucleo-vitals__val--${tone}` : ''}`; }

  void mountNucleoScene(sceneEl).then((mounted) => { scene = mounted; setVital('nucleo', 'ONLINE', 'ok'); }).catch((error: unknown) => { console.warn('[nucleo] cena 3D indisponível:', error); sceneEl.classList.add('nucleo-screen__scene--flat'); setVital('nucleo', 'MODO 2D', 'warn'); });
  const config = loadConfig();
  const vitalsEl = h('aside', { className: 'nucleo-vitals anim-fade-in', 'aria-label': 'Sinais vitais do Núcleo' }, h('div', { className: 'nucleo-vitals__title' }, '⬡ MARK XIII'), vitalRow('nucleo', 'NÚCLEO', '…'), vitalRow('rede', 'REDE', getNucleoUrl() ? 'CONECTANDO' : 'OFF'), vitalRow('eventos', 'EVENTOS', '0'), vitalRow('energia', 'ENERGIA', '—'), vitalRow('remoto', 'TELEMETRIA', '—'), vitalRow('bio', 'BIOMETRIA', '—'), vitalRow('modo', 'MODO IA', textOf(config.mode, 'local').toUpperCase()), vitalRow('motor', 'MOTOR', '…')); page.appendChild(vitalsEl);

  void nativeHermesStatus().then((status: NativeHermesStatus) => { if (status.available) setVital('motor', 'NATIVO (GGUF)', 'ok'); else if (status.downloading) setVital('motor', `NATIVO ⬇ ${Math.round(status.pct ?? 0)}%`, 'warn'); else setVital('motor', 'WEB (WEBLLM)', status.fatal ? 'warn' : undefined); }).catch(() => setVital('motor', 'WEB (WEBLLM)'));
  const offEngine = bus.on<{ engine?: string; reason?: string }>('hermes:engine', (event) => { if (event.engine === 'native') setVital('motor', 'NATIVO (GGUF)', 'ok'); else setVital('motor', 'WEB (WEBLLM)', event.reason ? 'warn' : undefined); });

  try {
    const navigatorWithBattery = navigator as Navigator & { getBattery?: () => Promise<BatteryManagerLike> };
    if (navigatorWithBattery.getBattery) void navigatorWithBattery.getBattery().then((battery) => { const update = (): void => { const percent = Math.round(battery.level * 100); setVital('energia', `${percent}%${battery.charging ? ' ⚡' : ''}`, percent < 20 && !battery.charging ? 'warn' : 'ok'); }; update(); battery.addEventListener('levelchange', update); battery.addEventListener('chargingchange', update); }).catch(() => undefined);
  } catch { /* Battery API é opcional */ }

  const panelBody = h('div', { className: 'nucleo-panel__body' }); const panelTitle = h('span', { className: 'nucleo-panel__title' }, ''); const panelEl = h('section', { className: 'nucleo-panel', hidden: true, 'aria-label': 'Função do Núcleo' }, h('div', { className: 'nucleo-panel__bar' }, panelTitle, h('span', { className: 'nucleo-panel__hint u-text-muted' }, 'diga "fechar" (ou Esc)')), panelBody); page.appendChild(panelEl); let panelToken = 0;
  function fecharPanel(): void { panelToken += 1; panelEl.hidden = true; empty(panelBody); }
  function abrirFuncao(fn: PanelFunction): void { const token = ++panelToken; panelTitle.textContent = fn.nome.toUpperCase(); panelEl.hidden = false; empty(panelBody); panelBody.appendChild(h('div', { className: 'nucleo-panel__loading' }, h('span', { className: 'gn-loading__orb' }), h('p', { className: 'u-text-muted' }, `Materializando ${fn.nome}…`))); void Promise.resolve().then(() => fn.load()).then((element) => { if (token !== panelToken) return; empty(panelBody); panelBody.appendChild(element); }).catch((error: unknown) => { if (token !== panelToken) return; console.error(`[nucleo] falha ao carregar "${fn.id}":`, error); empty(panelBody); panelBody.appendChild(h('p', { className: 'u-text-muted' }, 'Não deu pra materializar esta função agora.')); }); }

  const log = h('div', { className: 'nucleo-chat__log', role: 'log', 'aria-live': 'polite' }); const input = h('input', { className: 'nucleo-chat__input', placeholder: 'Fale com o J.A.R.V.I.S. — ex.: "mostrar memória", "gerar código", "corpo total"…', autocomplete: 'off', spellcheck: 'false', 'aria-label': 'Comando para o J.A.R.V.I.S.' });
  let sendCommand: () => Promise<void> = async () => undefined;
  const chatEl = h('div', { className: 'nucleo-chat' }, log, h('form', { className: 'nucleo-chat__dock', onsubmit: (event: Event) => { event.preventDefault(); void sendCommand(); } }, h('span', { className: 'nucleo-chat__sigil', 'aria-hidden': 'true' }, '◉'), input)); page.appendChild(chatEl);
  const convo: JarvisMessage[] = []; let pendingAction: PendingAction | null = null; let thinking: HTMLDivElement | null = null;
  function bubble(role: 'user' | 'jarvis' | 'tool', text: string): HTMLDivElement { const bubbleElement = h('div', { className: `nucleo-chat__msg nucleo-chat__msg--${role}` }, text); log.appendChild(bubbleElement); log.scrollTop = log.scrollHeight; while (log.children.length > 12) { const first = log.firstElementChild; if (first) log.removeChild(first); } return bubbleElement; }
  function think(on: boolean): void { if (on && !thinking) { thinking = bubble('jarvis', '…'); thinking.classList.add('nucleo-chat__msg--typing'); } else if (!on && thinking) { thinking.remove(); thinking = null; } }
  function configModelKey(current: JarvisConfig): string | null { return current.mode === 'hermes-agente' ? 'hermesAgentModel' : current.mode === 'webllm' ? 'webllmModel' : current.mode === 'ollama' ? 'ollamaModel' : current.mode === 'hermes-local' ? 'hermesLocalModel' : current.mode === 'claude' ? 'model' : null; }

  sendCommand = async (): Promise<void> => {
    const text = input.value.trim(); if (!text) return; input.value = ''; bubble('user', text); const lower = text.toLowerCase();
    if (lower === 'confirmar') { if (!pendingAction) { bubble('jarvis', 'Não há nada aguardando confirmação.'); return; } const action = pendingAction; pendingAction = null; try { bubble('jarvis', await action.executar()); } catch (error: unknown) { bubble('jarvis', `⚠ ${errorText(error)}`); } return; }
    if (lower === 'cancelar' && pendingAction) { pendingAction = null; bubble('jarvis', 'Ação cancelada — nada foi tocado.'); return; }
    if (pendingAction) { pendingAction = null; bubble('jarvis', '(ação pendente desarmada — nada foi tocado)'); }
    if (/^(fechar|ocultar|esconder|sair)( .*)?$/.test(lower)) { fecharPanel(); bubble('jarvis', 'Painel recolhido, senhor.'); return; }
    const modeMatch = lower.match(/^modo\s+([a-z-]+)$/); if (modeMatch) { if (isModo(modeMatch[1])) { saveConfig({ ...loadConfig(), mode: modeMatch[1] }); setVital('modo', modeMatch[1].toUpperCase()); bubble('jarvis', `Modo de IA → ${modeMatch[1]}.`); } else bubble('jarvis', `Modo desconhecido. Opções: ${MODOS.join(', ')}.`); return; }
    if (lower === 'motor') { const status = await nativeHermesStatus(); const version = status.appVersion ? ` · launcher v${status.appVersion}` : ''; if (status.available) { setVital('motor', 'NATIVO (GGUF)', 'ok'); const current = loadConfig(); if (current.mode === 'hermes-agente') bubble('jarvis', `✅ Motor NATIVO no controle — modelo ${status.model || 'GGUF'} (llama.cpp)${version}. O modo hermes-agente responde por ele.`); else { const owner = current.mode === 'hermes' ? 'o OpenRouter na nuvem (gasta créditos!)' : `"${current.mode}"`; bubble('jarvis', `✅ Motor NATIVO pronto — modelo ${status.model || 'GGUF'} (llama.cpp)${version}.\n⚠ MAS o modo de IA ativo é "${current.mode}" — quem responde o chat é ${owner}, não o motor da sua máquina. Diga "modo hermes-agente" pra usar o nativo (grátis, offline).`); } } else if (status.downloading) { setVital('motor', `NATIVO ⬇ ${Math.round(status.pct ?? 0)}%`, 'warn'); bubble('jarvis', `⬇ Baixando o modelo do motor nativo: ${Math.round(status.pct ?? 0)}% (~4,4 GB — segue em segundo plano; o WebLLM cobre enquanto isso)${version}. Diga "motor" de novo pra acompanhar.`); } else if (status.fatal) { setVital('motor', 'WEB (WEBLLM)', 'warn'); bubble('jarvis', `⚠ Motor nativo DESATIVADO nesta sessão${version}.\ncódigo: ${status.code || '?'}\nmotivo: ${(status.reason || '').slice(0, 160)}\ncorreção: ${status.hint || 'reinstalar o app'}`); } else { setVital('motor', 'WEB (WEBLLM)'); bubble('jarvis', `Motor: WebLLM (navegador)${version}. ${status.reason || 'Sem ponte com o app — no site, o nativo não existe.'}${status.error ? `\núltimo erro de download: ${status.error}` : ''}`); } return; }
    if (lower === 'arquivos' || lower === 'arquivista') { const status = await statusArquivos(); if (!status.disponivel) bubble('jarvis', 'O Arquivista mora no app (Baluarte Launcher) — no site eu não toco nos seus arquivos. Baixe em /baixar.'); else if (status.progresso?.ativo) bubble('jarvis', `🗂️ Varredura em andamento: ${status.progresso.varridos.toLocaleString('pt-BR')} arquivos vistos até agora…`); else bubble('jarvis', `🗂️ Arquivista pronto (read-only) — raiz: ${status.raiz || 'app'}.\nComandos: "arquivos <nome>" busca · "relatorio arquivos" inventário (.md + .txt em Documentos/Baluarte) · "analisar <pasta>" o-que-é-isto + duplicados + gordura · "ler <arquivo>" texto/código · "procurar <trecho> em <pasta>" busca por conteúdo.\n🛡️ Pastas pessoais (${(status.cofrePessoal ?? []).slice(0, 4).join(', ')}…) ficam de fora, sempre.`); return; }
    const fileSearch = lower.match(/^arquivos?\s+(.{2,})$/); if (fileSearch && fileSearch[1] !== 'arquivos') { bubble('jarvis', `🔎 Procurando "${fileSearch[1]}" nos seus arquivos…`); try { const result = await buscarArquivos(fileSearch[1]); if (!result.total) bubble('jarvis', `Nada com "${result.termo}" (varri ${result.stats.arquivos.toLocaleString('pt-BR')} arquivos${result.stats.protegidas ? `; ${result.stats.protegidas} pasta(s) pessoais ficaram de fora` : ''}).`); else { const lines = result.resultados.slice(0, 12).map((item) => `· ${item.caminho}`).join('\n'); bubble('jarvis', `🗂️ ${result.total} resultado(s) pra "${result.termo}"${result.tetoAtingido ? ' (mostrando o teto)' : ''}:\n${lines}${result.total > 12 ? `\n… e mais ${result.total - 12}.` : ''}${result.stats.parcial ? `\n⚠ varredura parcial (${result.stats.motivoParcial || 'sem detalhe'})` : ''}`); } } catch (error: unknown) { bubble('jarvis', `⚠ ${errorText(error)}`); } return; }
    const moveMatch = text.match(/^mover\s+(.+?)\s+(?:para|->)\s+(.+)$/i); if (moveMatch) { const [, from, to] = moveMatch; pendingAction = { executar: async () => { const result = await moverArquivo(from.trim(), to.trim()); return `✅ Movido:\n${result.de}\n→ ${result.para}`; } }; bubble('jarvis', `🚚 Mover:\n${from.trim()}\n→ ${to.trim()}\nDiga "confirmar" pra executar (ou "cancelar").`); return; }
    const deleteMatch = text.match(/^apagar\s+(.+)$/i); if (deleteMatch) { const target = deleteMatch[1].trim(); pendingAction = { executar: async () => { const result = await apagarArquivo(target); return `🗑️ Na lixeira do Baluarte (reversível, nada é apagado de verdade): ${result.original}\nid: ${result.id} — "restaurar ${result.id}" desfaz.`; } }; bubble('jarvis', `🗑️ Mandar pra LIXEIRA do Baluarte (reversível, nada é apagado de verdade):\n${target}\nDiga "confirmar" pra executar (ou "cancelar").`); return; }
    if (lower === 'sentinela' || lower === 'verificar pc' || lower === 'checar pc') { bubble('jarvis', '🛡️ Sentinela varrendo Downloads/Desktop e o autostart (read-only)…'); try { const result = await sentinelaPC(); const blocks: string[] = [`🛡️ Sentinela — varri: ${result.varridos.join(', ') || '(nenhum alvo achado)'}`]; if (result.duplaExtensao.length) blocks.push(`🔴 ISCAS (dupla extensão) — NÃO ABRA:\n${result.duplaExtensao.map((item) => `· ${item.caminho}`).join('\n')}`); if (result.executaveis.length) blocks.push(`🟡 Executáveis em Downloads/Desktop (confira se reconhece):\n${result.executaveis.slice(0, 8).map((item) => `· ${item.caminho} (${item.tamanho}, ${item.modificado})`).join('\n')}${result.executaveis.length > 8 ? `\n… e mais ${result.executaveis.length - 8}.` : ''}`); if (result.autostart.length) blocks.push(`⚡ Inicia junto com o sistema:\n${result.autostart.slice(0, 10).map((item) => `· ${item.item}`).join('\n')}`); if (result.pesadosParados.length) blocks.push(`⚪ Peso morto (200 MB+, 6+ meses parado):\n${result.pesadosParados.slice(0, 5).map((item) => `· ${item.caminho} (${item.tamanho}, ${item.meses}m)`).join('\n')}`); blocks.push(`${result.duplaExtensao.length ? '⚠' : '✅'} ${result.veredito}\n${result.nota}`); bubble('jarvis', blocks.join('\n\n')); } catch (error: unknown) { bubble('jarvis', `⚠ ${errorText(error)}`); } return; }
    if (lower === 'lixeira') { try { const result = await verLixeira(); if (!result.total) { bubble('jarvis', 'Lixeira do Baluarte vazia.'); return; } const lines = result.itens.slice(0, 10).map((item) => `· [${item.id}] ${item.original} (${item.quando.slice(0, 10)})`).join('\n'); bubble('jarvis', `🗑️ ${result.total} item(ns) na lixeira:\n${lines}\n"restaurar <id>" devolve pro lugar.`); } catch (error: unknown) { bubble('jarvis', `⚠ ${errorText(error)}`); } return; }
    const restoreMatch = lower.match(/^restaurar\s+(\S+)$/); if (restoreMatch) { pendingAction = { executar: async () => { const result = await restaurarArquivo(restoreMatch[1]); return `♻ Restaurado: ${result.restaurado}`; } }; bubble('jarvis', `♻ Restaurar o item [${restoreMatch[1]}] da lixeira pro caminho original.\nDiga "confirmar" pra executar (ou "cancelar").`); return; }
    const analyzeMatch = text.match(/^analisar\s+(.+)$/i); if (analyzeMatch) { bubble('jarvis', `🔬 Analisando "${analyzeMatch[1]}"…`); try { const result = await analisarPasta(analyzeMatch[1].trim()); const duplicates = result.duplicados.length ? `\n♻ Duplicados: ${result.duplicados.slice(0, 3).map((item) => `${item.tamanho} ×${item.arquivos.length}`).join(' · ')}` : ''; const waste = result.gordura.length ? `\n🏋 Gordura: ${result.gordura.slice(0, 3).map((item) => `${item.tamanho} parado há ${item.paradoHaMeses}m`).join(' · ')}` : ''; bubble('jarvis', `🗂️ ${result.caminho}\nTipo: ${result.tipo}${result.parcial ? ' (varredura parcial)' : ''}\n${result.arquivos.toLocaleString('pt-BR')} arquivos · ${result.pastas.toLocaleString('pt-BR')} pastas · ${result.tamanho}${result.protegidas ? ` · ${result.protegidas} protegida(s)` : ''}\nExtensões: ${result.topExtensoes.slice(0, 6).join(' ')}\nMaior: ${result.maiores[0] ? `${result.maiores[0].tamanho} — ${result.maiores[0].caminho}` : '—'}${duplicates}${waste}`); } catch (error: unknown) { bubble('jarvis', `⚠ ${errorText(error)}`); } return; }
    const readMatch = text.match(/^ler\s+(.+)$/i); if (readMatch) { try { const result = await lerArquivo(readMatch[1].trim()); const start = result.conteudo.split('\n').slice(0, 25).join('\n'); bubble('jarvis', `📄 ${result.caminho} (${result.linhas} linhas${result.truncado ? ', mostrando o começo' : ''}):\n${start}${result.linhas > 25 ? '\n…' : ''}`); } catch (error: unknown) { bubble('jarvis', `⚠ ${errorText(error)}`); } return; }
    const grepMatch = text.match(/^procurar\s+"?([^\"]{3,}?)"?(?:\s+em\s+(.+))?$/i); if (grepMatch) { bubble('jarvis', `🔎 Procurando "${grepMatch[1]}" DENTRO dos arquivos${grepMatch[2] ? ` de ${grepMatch[2]}` : ''}…`); try { const result = await grepArquivos(grepMatch[1], (grepMatch[2] || '.').trim()); if (!result.total) { bubble('jarvis', `Nada de "${result.termo}" em ${result.arquivosLidos.toLocaleString('pt-BR')} arquivos de texto lidos.`); return; } const lines = result.acertos.slice(0, 10).map((item) => `· ${item.caminho}:${item.linha} — ${item.trecho.slice(0, 80)}`).join('\n'); bubble('jarvis', `🔎 ${result.total} acerto(s)${result.tetoAtingido ? ' (teto)' : ''} pra "${result.termo}":\n${lines}${result.total > 10 ? `\n… e mais ${result.total - 10}.` : ''}`); } catch (error: unknown) { bubble('jarvis', `⚠ ${errorText(error)}`); } return; }
    if (/^relat[óo]rio( de)? arquivos$/.test(lower) || /^inventari(o|ar)( do pc)?$/.test(lower)) { bubble('jarvis', '🗂️ Gerando o inventário COMPLETO dos seus arquivos (read-only). Em discos grandes isso leva alguns minutos — diga "arquivos" pra acompanhar o progresso.'); try { const result = await relatorioArquivos(); const summary = result.resumo; bubble('jarvis', `✅ Inventário pronto${summary.parcial ? ` (PARCIAL — ${summary.motivoParcial || 'sem detalhe'})` : ''}:\n· ${summary.arquivos.toLocaleString('pt-BR')} arquivos em ${summary.pastas.toLocaleString('pt-BR')} pastas — ${summary.tamanho}\n· ${summary.protegidas} pasta(s) pessoais protegidas (fora do relatório) · ${summary.duracaoSeg}s\n📄 Relatório: ${result.relatorio}\n📜 Todos os caminhos: ${result.listagem}`); } catch (error: unknown) { bubble('jarvis', `⚠ ${errorText(error)}`); } return; }
    if (lower === 'hermes status') { const current = loadConfig(); bubble('jarvis', 'Sondando o Hermes local…'); try { const health = await healthHermesLocal(current); bubble('jarvis', `✅ Hermes local no ar em ${health.url} — ${health.models.length} modelo(s): ${health.models.slice(0, 5).join(', ') || '(nenhum carregado)'} . Diga "modo hermes-local" pra usar.`); } catch (error: unknown) { bubble('jarvis', `⚠ ${errorText(error)}`); } return; }
    const presetMatch = lower.match(/^hermes\s+(lmstudio|ollama|textgen)$/); if (presetMatch) { const preset = HERMES_LOCAL_PRESETS.find((item) => item.id === presetMatch[1]); if (!preset) { bubble('jarvis', 'Preset Hermes desconhecido.'); return; } saveConfig({ ...loadConfig(), hermesLocalUrl: preset.url }); bubble('jarvis', `Endpoint do Hermes local → ${preset.label} (${preset.url}). Diga "hermes status" pra testar.`); return; }
    const hermesUrl = lower.match(/^hermes\s+url\s+(\S+)$/); if (hermesUrl) { saveConfig({ ...loadConfig(), hermesLocalUrl: hermesUrl[1] }); bubble('jarvis', `Endpoint do Hermes local → ${hermesUrl[1]}. Diga "hermes status" pra testar.`); return; }
    if (lower === 'modelos' || lower === 'modelo') { const current = loadConfig(); const key = configModelKey(current); const configured = key ? current[key] : null; const actual = typeof configured === 'string' && configured ? configured : '(padrão)'; if (current.mode === 'hermes-local') { try { const ids = await listHermesLocalModels(current); const list = ids.map((id, index) => `${id === actual ? '▸' : ' '} ${index + 1}. ${id}`).join('\n'); bubble('jarvis', `Modo ativo: hermes-local · modelo: ${actual}\n${list || '(nenhum modelo carregado no servidor)'}\nDiga "modelo <nome>" pra trocar (vazio usa o carregado).`); } catch (error: unknown) { bubble('jarvis', `⚠ ${errorText(error)}`); } return; } const list = WEBLLM_MODELS.map((model, index) => `${model.id === actual ? '▸' : ' '} ${index + 1}. ${model.label}`).join('\n'); bubble('jarvis', `Modo ativo: ${current.mode} · modelo: ${actual}\n${list}\nDiga "modelo <nº ou nome>" pra trocar.`); return; }
    const modelMatch = lower.match(/^modelo\s+(.+)$/); if (modelMatch) { const current = loadConfig(); const key = configModelKey(current); if (!key) { bubble('jarvis', `O modo "${current.mode}" não usa modelo trocável por aqui.`); return; } const requested = modelMatch[1].trim(); const byIndex = /^\d+$/.test(requested) ? WEBLLM_MODELS[Number(requested) - 1] : undefined; const byName = WEBLLM_MODELS.find((model) => model.id.toLowerCase().includes(requested) || model.label.toLowerCase().includes(requested)); const target = byIndex ?? byName; if (current.mode === 'ollama' || current.mode === 'claude' || current.mode === 'hermes-local') { saveConfig({ ...current, [key]: requested }); bubble('jarvis', `Modelo do ${current.mode} → ${requested}.`); } else if (target) { saveConfig({ ...current, [key]: target.id }); bubble('jarvis', `Modelo → ${target.label}. A troca vale já na próxima mensagem (1º uso baixa o modelo).`); } else bubble('jarvis', 'Não achei esse modelo. Diga "modelos" pra ver a lista.'); return; }
    if (/^voz( on| off)?$/.test(lower)) { const enabled = lower === 'voz on' || (lower === 'voz' && !voiceEnabled()); setVoiceEnabled(enabled); const message = enabled ? `Voz ativada (${voiceLang()}${hasElevenKey() ? ' · ElevenLabs' : ' · navegador'}). Diga "voz off" pra silenciar.` : 'Voz desativada.'; bubble('jarvis', message); if (enabled) speak(message); return; }
    const languageMatch = lower.match(/^voz idioma\s+([a-z]{2}(-[a-z]{2})?)$/i); if (languageMatch) { const language = setVoiceLang(languageMatch[1]); bubble('jarvis', language ? `Idioma da voz → ${language}.` : `Idioma não suportado. Opções: ${VOICE_LANGS.join(', ')}.`); if (language && voiceEnabled()) speak(language.startsWith('pt') ? 'Idioma configurado, senhor.' : 'Language configured, sir.'); return; }
    const voiceKey = text.match(/^voz chave\s+(\S+)$/i); if (voiceKey) { setElevenKey(voiceKey[1]); bubble('jarvis', 'Chave da ElevenLabs guardada SÓ neste navegador. A voz de referência assume na próxima fala.'); return; }
    if (/^(silêncio|silencio|calar?)$/.test(lower)) { stopSpeaking(); bubble('jarvis', '…'); return; }
    const connectMatch = lower.match(/^conectar\s+(wss?:\/\/\S+)$/); if (connectMatch) { setNucleoUrl(connectMatch[1]); bubble('jarvis', `Ponte configurada: ${connectMatch[1]}. Conectando… (backend com NUCLEO_TOKEN? Diga "ponte token <valor>").`); return; }
    if (lower === 'desconectar') { setNucleoUrl(''); setVital('rede', 'OFF'); bubble('jarvis', 'Ponte desligada.'); return; }
    const tokenMatch = text.match(/^ponte\s+token\s+(\S+)$/i); if (tokenMatch) { setNucleoToken(tokenMatch[1]); bubble('jarvis', 'Token da ponte guardado (só neste navegador). Reconectando com ?token=…'); return; }
    const simulateMatch = lower.match(/^simular( evento)?( bio(metria)?| telemetria| voz| comando)?$/); if (simulateMatch) { const type = /bio/.test(lower) ? 'biometric' : /telemetria/.test(lower) ? 'telemetry' : 'command'; simulateNucleoEvent(type); bubble('jarvis', `Evento de demonstração (${type}) emitido — olhe os sinais vitais e a cena.`); return; }
    const requested = /^(mostrar?|abrir?|ativar?|exibir?|rodar?)\b/.test(lower) ? lower.replace(/^(mostrar?|abrir?|ativar?|exibir?|rodar?)\s*/, '') : lower; const panelFunction = FUNCOES.find((fn) => fn.match.test(requested)); if (panelFunction && requested.length < 40) { abrirFuncao(panelFunction); bubble('jarvis', panelFunction.id === 'vision' ? 'Ativando o Corpo Total, senhor.' : `${panelFunction.nome} materializado. Diga "fechar" quando terminar.`); return; }
    convo.push({ role: 'user', content: text }); think(true);
    try {
      const current = loadConfig(); const call: JarvisConfig = { ...current, systemPrompt: `${current.systemPrompt || ''}\n\n${getBaluarteBriefing({ compact: !['agente', 'hermes-agente'].includes(current.mode ?? '') })}\n\n## ESTADO ATUAL DO SITE (somente leitura)\n${getStatusText()}` }; let response: string; const onTool: JarvisToolCallback = (name, _input, result) => { think(false); bubble('tool', `⚙ ${name} → ${result?.ok ? 'ok' : 'erro'}`); think(true); };
      if (current.mode === 'agente') response = await processAgent(convo, call, onTool); else if (current.mode === 'hermes-agente') response = await processHermesAgent(convo, call, onTool, {}); else if (current.mode === 'claude') response = await processClaude(convo, call); else if (current.mode === 'ollama') response = await processOllama(convo, call); else if (current.mode === 'hermes-local') response = await processHermesLocal(convo, call); else if (current.mode === 'servidor') response = await processServer(convo, call); else if (current.mode === 'hermes') response = await processHermes(convo, call); else if (current.mode === 'claude-servidor') response = await processClaudeServer(convo, call); else if (current.mode === 'openclaw') response = await processOpenClaw(convo, call); else if (current.mode === 'webllm') { const module = await import('../utils/jarvis-webllm.js'); response = await module.processWebLLM(convo, call, { onProgress: (partial) => { if (thinking) thinking.textContent = `⬇ ${partial}`; }, onToken: (partial) => { if (thinking) thinking.textContent = partial; } }); } else { const local = processLocal(text); response = local.text; const action = local.action; if (action?.type === 'navigate') { const target = FUNCOES.find((fn) => action.payload.includes(fn.id)); if (target) abrirFuncao(target); } }
      think(false); convo.push({ role: 'assistant', content: response }); if (convo.length > 24) convo.splice(0, convo.length - 24); void import('../utils/nexus.js').then((module) => module.nexusMemory(`[${current.mode}] operador: ${text}\njarvis: ${response.slice(0, 4000)}`, ['conversa', 'jarvis', 'nucleo', current.mode ?? 'local'])).catch(() => undefined); bubble('jarvis', response); speak(response); scene?.pulse(360);
    } catch (error: unknown) { think(false); bubble('jarvis', `⚙ ${errorText(error)} — diga "modo local" pra respostas imediatas sem configuração.`); }
  };

  const onKey = (event: KeyboardEvent): void => { if (event.key === 'Escape' && !panelEl.hidden) fecharPanel(); }; document.addEventListener('keydown', onKey);
  function comandoRemoto(remoteText: string, source?: string): void { bubble('tool', `📡 ${source || 'remoto'}: ${remoteText}`); const lowerRemote = remoteText.toLowerCase().trim(); if (/^(fechar|ocultar|esconder)( .*)?$/.test(lowerRemote)) { fecharPanel(); return; } const requestedRemote = lowerRemote.replace(/^(mostrar?|abrir?|ativar?|exibir?|rodar?)\s*/, ''); const fn = FUNCOES.find((item) => item.match.test(requestedRemote)); if (fn) { abrirFuncao(fn); const message = `${fn.nome} materializado por comando remoto.`; bubble('jarvis', message); speak(message); } }
  let eventCount = 0;
  const offEvent = bus.on<NucleoEvent>('nucleo:event', (event) => { eventCount += 1; setVital('eventos', String(eventCount)); scene?.pulse(PULSE_MS[event.type] || 240); const payload = payloadRecord(event.payload); if (event.type === 'telemetry') { const metrics = payloadRecord(payload.metrics ?? payload); const battery = numberOf(metrics.battery); const keys = Object.keys(metrics).length; setVital('remoto', `${battery !== null ? `🔋${Math.round(battery * 100)}%` : `${keys} métrica(s)`} · ${event.source || '?'}`, 'ok'); } else if (event.type === 'biometric') { const heartRate = numberOf(payload.heartRate ?? payload.hr); if (heartRate !== null) { setVital('bio', `♥ ${heartRate} bpm · ${event.source || '?'}`, heartRate >= 120 || heartRate <= 45 ? 'warn' : 'ok'); scene?.setHeartRate(heartRate); } } else if ((event.type === 'command' || event.type === 'voice') && typeof payload.text === 'string') comandoRemoto(payload.text, event.source); });
  const offStatus = bus.on<NucleoStatus>('nucleo:status', (status) => { setVital('rede', status.connected ? 'ONLINE' : getNucleoUrl() ? 'RECONECTANDO' : 'OFF', status.connected ? 'ok' : undefined); });
  initNucleoLink(); initArquivosTools();
  const tab = textOf(args.tab ?? args.query?.tab); if (tab) { const fn = FUNCOES.find((item) => item.id === tab); if (fn) abrirFuncao(fn); }
  bubble('jarvis', 'Núcleo Mark XIII operacional. Às ordens, senhor.');
  if (typeof MutationObserver !== 'undefined') { const observer = new MutationObserver(() => { if (!document.contains(page)) { offEvent(); offStatus(); offEngine(); stopSpeaking(); document.removeEventListener('keydown', onKey); try { scene?.destroy(); } catch { /* cena já desmontada */ } observer.disconnect(); } }); observer.observe(document.body, { childList: true, subtree: true }); }
  return page;
}
