import '../styles/git-nexus.css';
import { h, empty } from '../utils/helpers.js';
import { router } from '../core/router.js';
import { buildImmersiveHero } from '../utils/immersive';

interface GitNexusArgs { readonly query?: Readonly<Record<string, string | undefined>>; readonly tab?: string; }
interface GitNexusModule { readonly gitNexusCockpit?: (args: GitNexusArgs) => HTMLElement; readonly gitNexusNucleo?: (args: GitNexusArgs) => HTMLElement; }
interface TeaserOptions { readonly failed?: boolean; }
function isNative(): boolean { return typeof window !== 'undefined' && window.baluarte?.native === true; }
function teaserFeat(icon: string, title: string, description: string): HTMLDivElement { return h('div', { className: 'gn-teaser__feat' }, h('div', { className: 'gn-teaser__feat-icon' }, icon), h('div', null, h('div', { className: 'gn-teaser__feat-title' }, title), h('div', { className: 'gn-teaser__feat-desc u-text-muted' }, description))); }
function gitNexusTeaser({ failed = false }: TeaserOptions = {}): HTMLDivElement { const page = h('div', { className: 'page-gitnexus' }); page.appendChild(buildImmersiveHero({ kicker: 'BALUARTE · NÚCLEO DE IA', title: 'Núcleo de IA', sub: 'GRAFO · JARVIS · MEMÓRIA · ML', variant: 'reactor', accent2: '#9d7bff', desc: ['O hub de IA do Baluarte — ', h('span', { className: 'u-text-cyan' }, 'grafo de código em 3D'), ', JARVIS, memória, segundo cérebro, ML, APIs e mais, num cockpit só. É a parte pesada da plataforma: roda completa no app desktop.'], hudLeft: '🔗 NÚCLEO · IA', hudRight: 'APP-ONLY' })); page.appendChild(h('div', { className: 'gn-teaser anim-fade-in' }, h('div', { className: 'gn-teaser__orb', 'aria-hidden': 'true' }, h('span', { className: 'gn-teaser__ring' }), h('span', { className: 'gn-teaser__ring gn-teaser__ring--b' }), h('span', { className: 'gn-teaser__dot' })), h('h2', { className: 'gn-teaser__title' }, failed ? 'Não deu pra abrir o Núcleo de IA aqui' : 'O Núcleo de IA roda no app'), h('p', { className: 'gn-teaser__lead' }, 'Pra manter o site leve e rápido, a seção de IA inteira — grafo 3D + mapas de código, JARVIS, memória, segundo cérebro, ML, Mini-LLM e o ', h('span', { className: 'u-text-cyan' }, 'motor real (gitnexus serve)'), ' — fica no ', h('strong', null, 'Baluarte Launcher'), ', onde dá pra rodar pesado sem as travas do navegador.'), h('div', { className: 'gn-teaser__feats' }, teaserFeat('🧠', 'Grafo + motor real', 'Git Nexus em 3D ligado ao motor (tree-sitter + LadybugDB).'), teaserFeat('◉', 'JARVIS & cérebro', 'Assistente, memória durável e o Segundo Cérebro, num cockpit.'), teaserFeat('📈', 'ML & Mini-LLM', 'Aprendizado da memória e o laboratório de LLM do zero.')), h('div', { className: 'gn-teaser__cta' }, h('button', { className: 'btn btn--primary', onclick: (): void => router.navigate('/baixar') }, '⬇ Baixar o app'), h('button', { className: 'btn', onclick: (): void => router.navigate('/codigo') }, '🔬 Ver o Raio-X do Código (web)')), h('p', { className: 'gn-teaser__hint u-text-muted' }, 'Já está no app? Abra esta página por lá que o Núcleo de IA carrega automaticamente.'))); return page; }
export function gitNexusGate(args: GitNexusArgs = {}): HTMLDivElement { if (!isNative()) return gitNexusTeaser(); const host = h('div', { className: 'page-gitnexus' }, h('div', { className: 'gn-loading anim-fade-in' }, h('span', { className: 'gn-loading__orb' }), h('p', { className: 'u-text-muted' }, 'Acordando o Núcleo de IA…'))); const legacy = args.query?.ui === 'cockpit'; const modulePromise = (legacy ? import('./git-nexus-cockpit') : import('./git-nexus-nucleo')) as Promise<GitNexusModule>; const render = legacy ? modulePromise.then((module) => module.gitNexusCockpit?.(args)) : modulePromise.then((module) => module.gitNexusNucleo?.(args)); render.then((element) => { empty(host); if (element) host.appendChild(element); }).catch((error: unknown) => { console.error('[git-nexus] falha ao carregar o Núcleo de IA:', error); empty(host); host.appendChild(gitNexusTeaser({ failed: true })); }); return host; }
