import '../styles/jarvis-vision.css';
import { h } from '../utils/helpers.js';
import type { VisionDetector, VisionHands, VisionHandsResults, VisionKeypoint, VisionPoint, VisionPose } from './jarvis-vision-api.d.ts';

interface VisionOptions { body: boolean; hands: boolean; hud: boolean; maxHands: number }
type LayerKey = 'body' | 'hands' | 'hud';
interface LayerDefinition { readonly k: LayerKey; readonly label: string }

function loadScript(src: string, timeoutMs = 20_000): Promise<void> {
  return new Promise((resolve, reject) => { const existing = document.querySelector<HTMLScriptElement>(`script[src="${src}"]`); if (existing?.dataset.loaded === '1') { resolve(); return; } existing?.remove(); const script = document.createElement('script'); const timer = window.setTimeout(() => { script.remove(); reject(new Error(`timeout: ${src}`)); }, timeoutMs); script.src = src; script.crossOrigin = 'anonymous'; script.onload = () => { window.clearTimeout(timer); script.dataset.loaded = '1'; resolve(); }; script.onerror = () => { window.clearTimeout(timer); reject(new Error(`falha: ${src}`)); }; document.head.appendChild(script); });
}

const POSE_CONNECTIONS: readonly (readonly [number, number])[] = [[5, 6], [5, 7], [7, 9], [6, 8], [8, 10], [5, 11], [6, 12], [11, 12], [11, 13], [13, 15], [12, 14], [14, 16]];
const HAND_CONNECTIONS: readonly (readonly [number, number])[] = [[0, 1], [1, 2], [2, 3], [3, 4], [0, 5], [5, 6], [6, 7], [7, 8], [5, 9], [9, 10], [10, 11], [11, 12], [9, 13], [13, 14], [14, 15], [15, 16], [13, 17], [0, 17], [17, 18], [18, 19], [19, 20]];
const PERSON_COLORS = ['#d4a24e', '#00c8ff', '#00ffaa', '#aaff00', '#e8c07a', '#ff8800', '#ff4400', '#cc00ff', '#ffff00', '#00ff44', '#ff0055', '#00aaff', '#88ff00', '#ff6600', '#9900ff', '#00ffcc', '#ff0099', '#44ff00', '#0055ff', '#ffaa00'] as const;
function telaX(wristX: number): number { return 1 - wristX; }
function decidirLadoPosicional(wristX: number): 'RIGHT' | 'LEFT' { return telaX(wristX) < 0.5 ? 'RIGHT' : 'LEFT'; }
function rotularMaos(maos: readonly { wristX: number }[]): Array<'RIGHT' | 'LEFT'> { if (maos.length === 2) { const [a, b] = maos; if (!a || !b) return []; const aMaisEsq = telaX(a.wristX) < telaX(b.wristX); return [aMaisEsq ? 'RIGHT' : 'LEFT', aMaisEsq ? 'LEFT' : 'RIGHT']; } return maos.map((mao) => decidirLadoPosicional(mao.wristX)); }
function isFingerUp(points: readonly VisionPoint[], tip: number, pip: number): boolean { const tipPoint = points[tip]; const pipPoint = points[pip]; return Boolean(tipPoint && pipPoint && tipPoint.y < pipPoint.y - 0.03); }
function isFingerDown(points: readonly VisionPoint[], tip: number, pip: number): boolean { const tipPoint = points[tip]; const pipPoint = points[pip]; return Boolean(tipPoint && pipPoint && tipPoint.y > pipPoint.y + 0.02); }
function isSpideyGesture(points: readonly VisionPoint[]): boolean { return isFingerUp(points, 8, 6) && isFingerDown(points, 12, 10) && isFingerDown(points, 16, 14) && isFingerUp(points, 20, 18); }
function isLGesture(points: readonly VisionPoint[]): boolean { const thumb = points[4]; const index = points[2]; return Boolean(thumb && index && Math.abs(thumb.x - index.x) > 0.08 && isFingerUp(points, 8, 6) && isFingerDown(points, 12, 10) && isFingerDown(points, 16, 14) && isFingerDown(points, 20, 18)); }
function isOpenHand(points: readonly VisionPoint[]): boolean { return isFingerUp(points, 8, 6) && isFingerUp(points, 12, 10) && isFingerUp(points, 16, 14) && isFingerUp(points, 20, 18); }
function isSixGesture(points: readonly VisionPoint[]): boolean { return isFingerUp(points, 8, 6) && isFingerUp(points, 12, 10) && isFingerDown(points, 16, 14) && isFingerDown(points, 20, 18); }
function isOkGesture(points: readonly VisionPoint[]): boolean { const thumb = points[4]; const index = points[8]; if (!thumb || !index) return false; const dx = thumb.x - index.x; const dy = thumb.y - index.y; return Math.sqrt(dx * dx + dy * dy) < 0.10 && isFingerUp(points, 12, 10) && isFingerUp(points, 16, 14) && isFingerUp(points, 20, 18); }
function isShakaGesture(points: readonly VisionPoint[]): boolean { const thumb = points[4]; const base = points[2]; return Boolean(thumb && base && thumb.y < base.y - 0.04 && isFingerDown(points, 8, 6) && isFingerDown(points, 12, 10) && isFingerDown(points, 16, 14) && isFingerUp(points, 20, 18)); }

class JarvisVision {
  readonly canvas: HTMLCanvasElement; readonly ctx: CanvasRenderingContext2D; readonly opts: VisionOptions; readonly statusEl: HTMLSpanElement; readonly metricsEl: HTMLDivElement;
  video: HTMLVideoElement | null = null; stream: MediaStream | null = null; detector: VisionDetector | null = null; hands: VisionHands | null = null; running = false; raf: number | null = null; frame = 0; poseResults: VisionPose[] = []; handResults: VisionHandsResults | null = null;
  readonly teiaAudio = new Audio('/vai-teia.mp3'); readonly shakaAudio = new Audio('/shaka.mp3'); teiaCooldown = 0; shakaCooldown = 0; fpsT = performance.now(); fpsN = 0; fps = 0; totalSkPts = 0; lastFrameT = 0; lastMetrics = '';
  constructor(canvas: HTMLCanvasElement, opts: VisionOptions, statusEl: HTMLSpanElement, metricsEl: HTMLDivElement) { const context = canvas.getContext('2d', { alpha: false, willReadFrequently: false }); if (!context) throw new Error('Canvas 2D indisponível'); this.canvas = canvas; this.ctx = context; this.opts = opts; this.statusEl = statusEl; this.metricsEl = metricsEl; this.teiaAudio.preload = 'auto'; this.shakaAudio.preload = 'auto'; }
  unlockAudio(): void { [this.teiaAudio, this.shakaAudio].forEach((audio) => { try { audio.muted = true; void audio.play().then(() => { audio.pause(); audio.currentTime = 0; audio.muted = false; }).catch(() => { audio.muted = false; }); } catch { audio.muted = false; } }); }
  async start(): Promise<boolean> { const setStatus = (text: string): void => { this.statusEl.textContent = text; }; this.unlockAudio(); setStatus('Carregando TF.js…'); try { await loadScript('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.20.0/dist/tf.min.js'); await loadScript('https://cdn.jsdelivr.net/npm/@tensorflow-models/pose-detection@2.1.3/dist/pose-detection.min.js'); } catch { setStatus('Sem acesso à CDN dos modelos — verifique a conexão e tente de novo.'); return false; }
    if (this.opts.hands) { try { await loadScript('https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands.js'); } catch { console.warn('[corpo-total] hands.js não carregou — sem mãos'); this.opts.hands = false; } }
    setStatus('Solicitando câmera…'); try { this.video = document.createElement('video'); this.video.muted = true; this.video.playsInline = true; this.stream = await navigator.mediaDevices.getUserMedia({ video: { width: { ideal: 1280, max: 1280 }, height: { ideal: 720, max: 720 }, frameRate: { ideal: 30, max: 30 }, facingMode: 'user' } }); this.video.srcObject = this.stream; await this.video.play(); } catch { setStatus('Câmera negada ou indisponível.'); return false; }
    const video = this.video; const width = video.videoWidth || 1280; const height = video.videoHeight || 720; this.canvas.width = width; this.canvas.height = height;
    if (this.opts.body) { setStatus('Inicializando MoveNet MultiPose…'); try { const tf = window.tf; const poseDetection = window.poseDetection; if (!tf || !poseDetection) throw new Error('TF.js ou pose-detection indisponível'); await tf.setBackend('webgl'); await tf.ready(); this.detector = await poseDetection.createDetector(poseDetection.SupportedModels.MoveNet, { modelType: poseDetection.movenet.modelType.MULTIPOSE_LIGHTNING, enableTracking: true, trackerType: poseDetection.TrackerType.BoundingBox }); } catch { setStatus('Falha ao criar detector de poses.'); return false; } }
    if (this.opts.hands) { setStatus('Inicializando mãos…'); try { const Hands = window.Hands; if (!Hands) throw new Error('window.Hands indisponível (CDN)'); this.hands = new Hands({ locateFile: (file) => `https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}` }); this.hands.setOptions({ maxNumHands: this.opts.maxHands || 80, modelComplexity: 1, minDetectionConfidence: 0.5, minTrackingConfidence: 0.5 }); this.hands.onResults((results) => { this.handResults = results; }); await this.hands.initialize(); } catch (error: unknown) { console.warn('[corpo-total] mãos indisponíveis — seguindo só com o corpo:', error instanceof Error ? error.message : error); try { this.hands?.close(); } catch { /* teardown parcial */ } this.hands = null; this.opts.hands = false; } }
    this.running = true; setStatus('● RASTREANDO'); this.loop(0); return true;
  }
  setOpt(key: LayerKey, value: boolean): void { this.opts[key] = value; }
  loop(timestamp = 0): void { if (!this.running) return; this.raf = window.requestAnimationFrame((time) => this.loop(time)); if (timestamp - this.lastFrameT < 14) return; this.lastFrameT = timestamp; if (document.hidden) return; if (!this.video || this.video.readyState < 2) return; this.frame += 1; const video = this.video; if (this.opts.body && this.detector && this.frame % 3 === 0) void this.detector.estimatePoses(video, { flipHorizontal: false, maxPoses: 20 }).then((poses) => { this.poseResults = poses || []; }).catch(() => undefined); if (this.opts.hands && this.hands && this.frame % 4 === 0) { try { this.hands.send({ image: video }); } catch { /* frame descartado */ } } try { this.render(); } catch { /* render defensivo */ } this.fpsN += 1; const now = performance.now(); if (now - this.fpsT >= 1000) { this.fps = Math.round((this.fpsN * 1000) / (now - this.fpsT)); this.fpsN = 0; this.fpsT = now; this.updateMetrics(); } }
  render(): void { const video = this.video; if (!video) return; const { ctx, canvas } = this; const width = canvas.width; const height = canvas.height; ctx.save(); ctx.scale(-1, 1); ctx.drawImage(video, -width, 0, width, height); ctx.restore(); ctx.fillStyle = 'rgba(0,8,16,0.25)'; ctx.fillRect(0, 0, width, height); if (this.opts.hud) this.renderHUD(width, height); if (this.opts.body) this.renderPoses(width, height); if (this.opts.hands) this.renderHands(width, height); }
  renderPoses(width: number, height: number): void { const poses = this.poseResults; if (!poses.length || !this.video) return; const { ctx } = this; const qx = (x1: number, cx: number, x2: number, t: number): number => (1 - t) * (1 - t) * x1 + 2 * (1 - t) * t * cx + t * t * x2; const qy = (y1: number, cy: number, y2: number, t: number): number => (1 - t) * (1 - t) * y1 + 2 * (1 - t) * t * cy + t * t * y2; const interp = 4167; const score = 0.35; const major = new Uint8Array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]); let totalPoints = 0; const scaleX = width / (this.video.videoWidth || width); const scaleY = height / (this.video.videoHeight || height); const toX = (keypoint: VisionKeypoint): number => width - keypoint.x * scaleX; const toY = (keypoint: VisionKeypoint): number => keypoint.y * scaleY;
    poses.forEach((pose, personIndex) => { const keypoints = pose.keypoints; const color = PERSON_COLORS[personIndex % PERSON_COLORS.length] ?? PERSON_COLORS[0]; const px = new Float32Array(17); const py = new Float32Array(17); const valid = new Uint8Array(17); let validCount = 0; for (let index = 0; index < 17; index += 1) { const keypoint = keypoints[index]; if (keypoint && (keypoint.score ?? 1) >= score) { px[index] = toX(keypoint); py[index] = toY(keypoint); valid[index] = 1; validCount += 1; } } if (validCount < 3) return; ctx.shadowBlur = 0; ctx.strokeStyle = 'rgba(212,162,78,0.10)'; ctx.lineWidth = 8; ctx.beginPath(); POSE_CONNECTIONS.forEach(([a, b]) => { if (!valid[a] || !valid[b]) return; const x1 = px[a]; const y1 = py[a]; const x2 = px[b]; const y2 = py[b]; const mx = (x1 + x2) * 0.5; const my = (y1 + y2) * 0.5; const dx = x2 - x1; const dy = y2 - y1; const length = Math.sqrt(dx * dx + dy * dy) || 1; ctx.moveTo(x1, y1); ctx.quadraticCurveTo(mx - (dy / length) * length * 0.07, my + (dx / length) * length * 0.07, x2, y2); }); ctx.stroke(); ctx.shadowColor = color; ctx.shadowBlur = 6; ctx.strokeStyle = color; ctx.lineWidth = 1.5; ctx.beginPath(); POSE_CONNECTIONS.forEach(([a, b]) => { if (!valid[a] || !valid[b]) return; const x1 = px[a]; const y1 = py[a]; const x2 = px[b]; const y2 = py[b]; const mx = (x1 + x2) * 0.5; const my = (y1 + y2) * 0.5; const dx = x2 - x1; const dy = y2 - y1; const length = Math.sqrt(dx * dx + dy * dy) || 1; ctx.moveTo(x1, y1); ctx.quadraticCurveTo(mx - (dy / length) * length * 0.07, my + (dx / length) * length * 0.07, x2, y2); }); ctx.stroke(); ctx.shadowBlur = 0; ctx.fillStyle = color; POSE_CONNECTIONS.forEach(([a, b]) => { if (!valid[a] || !valid[b]) return; const x1 = px[a]; const y1 = py[a]; const x2 = px[b]; const y2 = py[b]; const mx = (x1 + x2) * 0.5; const my = (y1 + y2) * 0.5; const dx = x2 - x1; const dy = y2 - y1; const length = Math.sqrt(dx * dx + dy * dy) || 1; const controlX = mx - (dy / length) * length * 0.07; const controlY = my + (dx / length) * length * 0.07; for (let index = 1; index < interp; index += 1) { const t = index / interp; ctx.fillRect(qx(x1, controlX, x2, t) - 1.5, qy(y1, controlY, y2, t) - 1.5, 3, 3); totalPoints += 1; } }); for (let index = 0; index < 17; index += 1) { if (!valid[index]) continue; const isMajor = major[index] === 1; const radius = isMajor ? 5 : 3; if (isMajor) { ctx.beginPath(); ctx.arc(px[index], py[index], radius + 4, 0, Math.PI * 2); ctx.fillStyle = 'rgba(212,162,78,0.15)'; ctx.shadowBlur = 0; ctx.fill(); } ctx.beginPath(); ctx.arc(px[index], py[index], radius, 0, Math.PI * 2); ctx.fillStyle = color; ctx.shadowColor = color; ctx.shadowBlur = isMajor ? 12 : 6; ctx.fill(); totalPoints += 1; } if (valid[0]) { ctx.shadowBlur = 0; ctx.font = 'bold 11px monospace'; ctx.fillStyle = color; ctx.fillText(`P${personIndex + 1}`, px[0] - 8, py[0] - 24); } }); ctx.shadowBlur = 0; this.totalSkPts = totalPoints; }
  renderHands(width: number, height: number): void { const list = this.handResults?.multiHandLandmarks; if (!list) return; const { ctx } = this; const x = (point: VisionPoint): number => (1 - point.x) * width; const y = (point: VisionPoint): number => point.y * height; const tips = new Set([4, 8, 12, 16, 20]); const handInterp = 2380; const labels = rotularMaos(list.map((landmarks) => ({ wristX: landmarks[0]?.x ?? 0.5 })));
    list.forEach((landmarks, handIndex) => { const spidey = isSpideyGesture(landmarks); const shaka = isShakaGesture(landmarks); const lineColor = spidey ? '#ff3300' : shaka ? '#ffaa00' : 'rgba(0,255,136,0.8)'; const dotColor = spidey ? '#ff6600' : shaka ? '#ffcc44' : '#00ff88'; const glowColor = spidey ? '#ff2200' : shaka ? '#ff7700' : '#00ff88'; const fancy = spidey || shaka; ctx.shadowColor = glowColor; ctx.shadowBlur = fancy ? 18 : 8; ctx.strokeStyle = lineColor; ctx.lineWidth = fancy ? 2.5 : 1.8; ctx.beginPath(); HAND_CONNECTIONS.forEach(([a, b]) => { const first = landmarks[a]; const second = landmarks[b]; if (!first || !second) return; ctx.moveTo(x(first), y(first)); ctx.lineTo(x(second), y(second)); }); ctx.stroke(); ctx.shadowBlur = 0; ctx.fillStyle = dotColor; HAND_CONNECTIONS.forEach(([a, b]) => { const first = landmarks[a]; const second = landmarks[b]; if (!first || !second) return; const ax = x(first); const ay = y(first); const bx = x(second); const by = y(second); for (let index = 1; index < handInterp; index += 1) { const t = index / handInterp; ctx.fillRect(ax + (bx - ax) * t - 1, ay + (by - ay) * t - 1, 2, 2); } }); landmarks.forEach((point, index) => { const wrist = index === 0; const tip = tips.has(index); ctx.beginPath(); ctx.arc(x(point), y(point), wrist ? 6 : tip ? 4.5 : 2.5, 0, Math.PI * 2); ctx.fillStyle = wrist ? '#e8c07a' : dotColor; ctx.shadowColor = wrist ? '#e8c07a' : glowColor; ctx.shadowBlur = wrist ? 14 : fancy ? 12 : 6; ctx.fill(); }); const label = labels[handIndex] ?? 'HAND'; ctx.shadowBlur = 0; ctx.font = 'bold 13px monospace'; const wrist = landmarks[0]; if (!wrist) return; const labelX = x(wrist) - 20; const labelY = y(wrist) + 28; ctx.fillStyle = 'rgba(0,12,24,0.6)'; ctx.fillRect(labelX - 2, labelY - 13, ctx.measureText(label).width + 6, 17); ctx.fillStyle = spidey ? '#ff4400' : shaka ? '#ffaa00' : 'rgba(0,255,136,0.95)'; ctx.fillText(label, labelX, labelY); if (spidey) { ctx.font = 'bold 15px monospace'; ctx.fillStyle = '#ff4400'; ctx.shadowColor = '#ff2200'; ctx.shadowBlur = 10; ctx.fillText('🕷 VAI TEIA!', x(wrist) - 40, y(wrist) - 40); } else if (shaka) { ctx.font = 'bold 15px monospace'; ctx.fillStyle = '#ffaa00'; ctx.shadowColor = '#ff7700'; ctx.shadowBlur = 10; ctx.fillText('🤙 SHAKA!', x(wrist) - 40, y(wrist) - 40); } }); ctx.shadowBlur = 0; const now = performance.now(); if (list.some((landmarks) => isSpideyGesture(landmarks)) && now > this.teiaCooldown) { this.teiaCooldown = now + 2000; this.teiaAudio.currentTime = 0; void this.teiaAudio.play().catch(() => undefined); } if (list.some((landmarks) => isShakaGesture(landmarks)) && now > this.shakaCooldown) { this.shakaCooldown = now + 2000; this.shakaAudio.currentTime = 0; void this.shakaAudio.play().catch(() => undefined); } }
  renderHUD(width: number, height: number): void { const { ctx } = this; ctx.shadowBlur = 0; ctx.strokeStyle = 'rgba(212,162,78,0.04)'; ctx.lineWidth = 1; ctx.beginPath(); for (let x = 0; x <= width; x += width / 12) { ctx.moveTo(x, 0); ctx.lineTo(x, height); } for (let y = 0; y <= height; y += height / 8) { ctx.moveTo(0, y); ctx.lineTo(width, y); } ctx.stroke(); const length = 32; const centerX = width / 2; const centerY = height / 2; ctx.strokeStyle = 'rgba(212,162,78,0.35)'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(length, 0); ctx.lineTo(0, 0); ctx.lineTo(0, length); ctx.moveTo(width - length, 0); ctx.lineTo(width, 0); ctx.lineTo(width, length); ctx.moveTo(0, height - length); ctx.lineTo(0, height); ctx.lineTo(length, height); ctx.moveTo(width, height - length); ctx.lineTo(width, height); ctx.lineTo(width - length, height); ctx.stroke(); ctx.strokeStyle = 'rgba(212,162,78,0.22)'; ctx.beginPath(); ctx.arc(centerX, centerY, 26, 0, Math.PI * 2); ctx.moveTo(centerX - 36, centerY); ctx.lineTo(centerX - 12, centerY); ctx.moveTo(centerX + 12, centerY); ctx.lineTo(centerX + 36, centerY); ctx.moveTo(centerX, centerY - 36); ctx.lineTo(centerX, centerY - 12); ctx.moveTo(centerX, centerY + 12); ctx.lineTo(centerX, centerY + 36); ctx.stroke(); ctx.fillStyle = 'rgba(212,162,78,0.6)'; ctx.font = '13px monospace'; ctx.fillText('J.A.R.V.I.S · MULTI-BODY TRACKING', 14, 24); ctx.fillText(new Date().toLocaleTimeString(), width - 96, 24); }
  updateMetrics(): void { const people = this.poseResults.length; const hands = this.handResults?.multiHandLandmarks?.length ?? 0; const points = this.totalSkPts + hands * 21; const format = (value: number): string => value >= 1000 ? `${(value / 1000).toFixed(1)}k` : String(value); const html = `<span>FPS <b>${this.fps}</b></span><span>Pessoas <b>${people}/20</b></span><span>Mãos <b>${hands}</b></span><span>Pontos <b>${format(points)}</b></span>`; if (html !== this.lastMetrics) { this.metricsEl.innerHTML = html; this.lastMetrics = html; } }
  stop(): void { this.running = false; if (this.raf !== null) window.cancelAnimationFrame(this.raf); this.raf = null; this.stream?.getTracks().forEach((track) => track.stop()); try { this.detector?.dispose(); } catch { /* dispose defensivo */ } try { this.hands?.close(); } catch { /* close defensivo */ } try { window.tf?.disposeVariables(); } catch { /* TF opcional */ } this.stream = null; this.video = null; this.detector = null; this.hands = null; this.poseResults = []; this.handResults = null; }
}

let engine: JarvisVision | null = null;
function cleanup(): void { engine?.stop(); engine = null; }

export function jarvisVisionPage(): HTMLDivElement {
  cleanup(); const opts: VisionOptions = { body: true, hands: true, hud: true, maxHands: 80 }; const canvas = h('canvas', { className: 'jv-canvas' }); const status = h('span', { className: 'jv-status' }, 'Câmera parada.'); const metrics = h('div', { className: 'jv-metrics' }); let running = false;
  let startButton!: HTMLButtonElement; startButton = h('button', { className: 'btn btn--primary', onclick: async () => { if (running) { engine?.stop(); engine = null; running = false; startButton.textContent = '▶ Ativar JARVIS'; status.textContent = 'Câmera parada.'; metrics.innerHTML = ''; return; } startButton.disabled = true; engine = new JarvisVision(canvas, { ...opts }, status, metrics); let ok = false; try { ok = await engine.start(); } catch (error: unknown) { console.warn('[corpo-total] falha inesperada no start:', error); status.textContent = 'Falha inesperada ao iniciar — tente de novo (detalhes no console).'; } finally { startButton.disabled = false; } if (ok) { running = true; startButton.textContent = '⏹ Desativar'; } else { try { engine?.stop(); } catch { /* ok */ } engine = null; } } }, '▶ Ativar JARVIS');
  const layerDefs: readonly LayerDefinition[] = [{ k: 'body', label: '🦴 Esqueleto' }, { k: 'hands', label: '✋ Mãos' }, { k: 'hud', label: '🎯 HUD' }]; const layerButtons = layerDefs.map(({ k, label }) => { let button!: HTMLButtonElement; button = h('button', { className: `jv-toggle${opts[k] ? ' is-on' : ''}`, onclick: () => { opts[k] = !opts[k]; button.classList.toggle('is-on', opts[k]); engine?.setOpt(k, opts[k]); } }, label); return button; });
  const handsSelect = h('select', { className: 'jv-select', onchange: (event: Event) => { if (!(event.target instanceof HTMLSelectElement)) return; opts.maxHands = Number(event.target.value); if (engine?.hands) engine.hands.setOptions({ maxNumHands: opts.maxHands, modelComplexity: 1, minDetectionConfidence: 0.5, minTrackingConfidence: 0.5 }); } }, ...[2, 4, 8, 10, 20, 40, 60, 80].map((value) => h('option', { value: String(value), selected: value === 80 }, `${value} mãos`)));
  const wrap = h('div', { className: 'jv-page page-wrap' }, h('div', { className: 'page-hero' }, h('h1', null, '🤖 JARVIS · Rastreamento Multi-Corporal'), h('p', { className: 'u-text-muted' }, 'Até 20 pessoas simultâneas (MoveNet MultiPose LIGHTNING) com esqueleto de até 50000 pontos por pessoa + curvas suaves + até 80 mãos, tudo em tempo real.')), h('div', { className: 'jv-bar' }, startButton, ...layerButtons, h('label', { className: 'jv-label' }, 'Máx mãos:', handsSelect), status), metrics, h('div', { className: 'jv-viewport' }, canvas), h('div', { className: 'jv-legend' }, h('span', null, h('i', { style: { background: '#d4a24e' } }), 'Pessoa 1'), h('span', null, h('i', { style: { background: '#00ffaa' } }), 'Pessoa 2'), h('span', null, h('i', { style: { background: '#aaff00' } }), 'Pessoa 3+'), h('span', null, h('i', { style: { background: '#00ff88' } }), 'Mãos'), h('span', null, h('i', { style: { background: '#e8c07a' } }), 'Pulso')), h('div', { className: 'jv-info' }, h('p', null, '⚡ TF.js MoveNet MultiPose carrega via CDN na primeira ativação (~8-12s). Depois fica em cache do browser.'), h('p', null, '💡 Afaste-se da câmera para capturar o corpo todo. Cada pessoa detectada recebe uma cor diferente.')));
  const observer = new MutationObserver(() => { if (!document.body.contains(wrap)) { cleanup(); observer.disconnect(); } }); observer.observe(document.body, { childList: true, subtree: true }); return wrap;
}
