import { h } from '../utils/helpers.js';
import { router } from '../core/router.js';
import { lineIcon } from '../utils/icons.js';
import { buildImmersiveHero } from '../utils/immersive.js';
import { fetchWikiSummary, wikiArticleUrl } from '../utils/wikipedia.js';
import { fetchMilCuration } from '../utils/mil-curation.js';
import type { MilCurationMap } from '../utils/mil-curation.js';
import type { WikiSummary } from '../utils/wikipedia.js';
import '../styles/centro-militar.css';

interface MilitaryTopic { readonly id: string; readonly label: string; readonly icon: string; readonly route: string; readonly wiki: string; readonly desc: string; }
interface TopicRef { readonly sec: HTMLElement; readonly tocItem: HTMLElement; readonly wikiBox: HTMLDivElement; }
const TOPICS: readonly MilitaryTopic[] = [
  { id: 'enciclopedia', label: 'Enciclopédia Militar', icon: 'book', route: '/enciclopedia-militar', wiki: 'Militar', desc: 'Visão geral: o que é uma força armada, seus ramos, organização e papel na sociedade.' },
  { id: 'forcas-armadas', label: 'Forças Armadas do Mundo', icon: 'globe', route: '/forcas-armadas', wiki: 'Forças armadas', desc: 'Exércitos, marinhas e forças aéreas dos países do mundo.' },
  { id: 'orcamentos', label: 'Orçamentos Militares', icon: 'bars', route: '/orcamentos-militares', wiki: 'Despesa militar', desc: 'Quanto cada país gasta em defesa — em % do PIB e em valores.' },
  { id: 'poder', label: 'Rankings de Poder', icon: 'award', route: '/poder-militar', wiki: 'Potência militar', desc: 'Comparação do poder militar entre as nações.' },
  { id: 'arsenal-exp', label: 'Arsenal Expandido', icon: 'swords', route: '/arsenal-expandido', wiki: 'Armamento', desc: 'Catálogo ampliado de armamentos e equipamentos.' },
  { id: 'especiais', label: 'Forças Especiais', icon: 'helmet', route: '/forcas-especiais', wiki: 'Forças especiais', desc: 'Unidades de elite e operações especiais.' },
  { id: 'organizacao', label: 'Organização Militar', icon: 'sitemap', route: '/organizacao-militar', wiki: 'Organização militar', desc: 'Hierarquia e patentes — do esquadrão ao grupo de exércitos.' },
  { id: 'tecnologia', label: 'Tecnologia Militar', icon: 'rocket', route: '/tecnologia-militar', wiki: 'Tecnologia militar', desc: 'Sistemas de combate por domínio — do soldado conectado às armas hipersônicas.' },
  { id: 'taticas', label: 'Táticas & Estratégias', icon: 'strategy', route: '/taticas-estrategias', wiki: 'Tática militar', desc: 'Da tática no campo de batalha à grande estratégia.' },
  { id: 'historia', label: 'História Militar', icon: 'scroll', route: '/historia-militar', wiki: 'História militar', desc: 'A evolução da guerra e das instituições militares.' },
  { id: 'armas-pais', label: 'Armas por País', icon: 'crosshair', route: '/armas-por-pais', wiki: 'Arma', desc: 'Armamentos catalogados por país de origem.' },
  { id: 'guerras', label: 'Guerras & Conflitos', icon: 'globe', route: '/guerras-conflitos', wiki: 'Guerra', desc: 'Conflitos armados ao longo da história.' },
  { id: 'batalhas', label: 'Batalhas Históricas', icon: 'shield', route: '/batalhas-historicas', wiki: 'Batalha', desc: 'As batalhas que mudaram o curso da história.' },
  { id: 'arsenal', label: 'Arsenal', icon: 'target', route: '/arsenal', wiki: 'Arsenal', desc: 'O catálogo militar completo do Baluarte.' },
];
function fillWiki(box: HTMLDivElement, topic: MilitaryTopic): void { fetchWikiSummary(topic.wiki).then((data: WikiSummary) => { box.replaceChildren(); if (data.thumb) box.appendChild(h('img', { className: 'mil-wiki__thumb', src: data.thumb, alt: '', loading: 'lazy' })); box.appendChild(h('p', { className: 'mil-wiki__extract' }, data.extract || topic.desc)); box.appendChild(h('div', { className: 'mil-wiki__foot' }, h('a', { className: 'mil-wiki__more', href: data.url, target: '_blank', rel: 'noopener' }, 'Ler na Wikipédia →'), h('span', { className: 'mil-wiki__lic' }, 'Fonte: Wikipédia · CC BY-SA'))); }).catch(() => { box.replaceChildren(h('a', { className: 'mil-wiki__more', href: wikiArticleUrl(topic.wiki), target: '_blank', rel: 'noopener' }, `Ler "${topic.wiki}" na Wikipédia →`)); }); }
function lazyFillWiki(section: HTMLElement, box: HTMLDivElement, topic: MilitaryTopic, onCleanup: (cleanup: () => void) => void): void { if (typeof IntersectionObserver === 'undefined') { fillWiki(box, topic); return; } let done = false; const observer = new IntersectionObserver((entries) => { if (done) return; if (entries.some((entry) => entry.isIntersecting)) { done = true; observer.disconnect(); fillWiki(box, topic); } }, { rootMargin: '250px' }); observer.observe(section); onCleanup(() => observer.disconnect()); }
export function militarPage(): HTMLDivElement { const cleanups: Array<() => void> = []; const onCleanup = (cleanup: () => void): void => { cleanups.push(cleanup); }; const page = h('div', { className: 'page-militar' }); page.appendChild(buildImmersiveHero({ kicker: 'BALUARTE · CENTRO MILITAR', title: 'Centro Militar', sub: 'TUDO NUM LUGAR SÓ', desc: `${TOPICS.length} frentes militares reunidas — cada uma com extrato vivo da Wikipédia e link pra página completa.`, variant: 'scope', hudLeft: `🎖 ${TOPICS.length} FRENTES`, hudRight: 'ENCICLOPÉDIA' })); const tocList = h('nav', { className: 'mil-toc__list' }); const toc = h('aside', { className: 'mil-toc' }, h('div', { className: 'mil-toc__title' }, 'Conteúdo'), tocList); const sections = h('div', { className: 'mil-sections' }); const byId: Record<string, TopicRef> = {};
  TOPICS.forEach((topic) => { const tocItem = h('button', { className: 'mil-toc__item', onclick: (): void => document.getElementById(`sec-${topic.id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }, h('span', { className: 'mil-toc__ico', html: lineIcon(topic.icon) }), h('span', null, topic.label)); tocList.appendChild(tocItem); const wikiBox = h('div', { className: 'mil-wiki' }, h('span', { className: 'mil-wiki__loading' }, 'Carregando da Wikipédia…')); const section = h('section', { id: `sec-${topic.id}`, className: 'mil-section' }, h('div', { className: 'mil-section__head' }, h('span', { className: 'mil-section__ico', html: lineIcon(topic.icon) }), h('h2', { className: 'mil-section__title' }, topic.label), h('button', { className: 'mil-section__open', onclick: (): void => router.navigate(topic.route) }, 'abrir página completa →')), h('p', { className: 'mil-section__desc' }, topic.desc), wikiBox); sections.appendChild(section); lazyFillWiki(section, wikiBox, topic, onCleanup); byId[topic.id] = { sec: section, tocItem, wikiBox }; });
  fetchMilCuration().then((curation: MilCurationMap) => { Object.keys(curation).forEach((id) => { const reference = byId[id]; const entry = curation[id]; if (!reference || !entry) return; if (entry.featured) { reference.sec.classList.add('is-featured'); reference.tocItem.classList.add('is-featured'); } if (entry.note) reference.sec.insertBefore(h('div', { className: 'mil-note' }, h('span', { className: 'mil-note__tag' }, '✦ Nota do operador'), entry.note), reference.wikiBox); }); });
  page.appendChild(h('div', { className: 'mil-layout' }, toc, sections)); page.appendChild(h('p', { className: 'mil-credit' }, 'Extratos de texto da ', h('a', { href: 'https://pt.wikipedia.org', target: '_blank', rel: 'noopener' }, 'Wikipédia'), ' sob licença ', h('a', { href: 'https://creativecommons.org/licenses/by-sa/4.0/', target: '_blank', rel: 'noopener' }, 'CC BY-SA 4.0'), ' — as páginas completas de cada frente seguem no Baluarte.')); if (typeof MutationObserver !== 'undefined') { const observer = new MutationObserver(() => { if (!document.contains(page)) { cleanups.splice(0).forEach((cleanup) => { try { cleanup(); } catch {} }); observer.disconnect(); } }); observer.observe(document.body, { childList: true, subtree: true }); } return page; }
