import '../styles/musicas.css';
import { h, empty, cx } from '../utils/helpers.js';
import { buildImmersiveHero } from '../utils/immersive.js';
import { storage } from '../core/storage.js';
import { toast } from '../utils/toast.js';
import { saveBookmark, loadBookmark } from '../core/media-sync.js';
import { SOUNDCLOUD_TRACKS } from '../data/soundcloud-tracks.js';
import type { SoundCloudTrack } from '../data/soundcloud-tracks.js';
import { ALBUNS } from '../data/albuns.js';
import type { Album, AlbumTrack } from '../data/albuns.js';
import { MUSICAS_PROPRIAS, MUSICAS_LOCAIS, SUNO_PERFIL } from '../data/musicas-proprias.js';
import type { MusicaLocal, MusicaPropria } from '../data/musicas-proprias.js';
import { addFiles, listTracks, getBlob, removeTrack, clearAll, formatSize, offlineAudioSupported } from '../utils/offline-audio.js';
import type { OfflineTrack } from '../utils/offline-audio.js';
import type { SoundCloudWidget, SpotifyController, SpotifyEmbedAPI } from '../utils/music-embeds.d.ts';

type SpotifyEmbedType = 'track' | 'album' | 'playlist' | 'artist' | 'episode' | 'show';
type CustomMusic = SpotifyCustomMusic | SoundCloudCustomMusic;
interface SpotifyCustomMusic { kind: 'spotify'; type: SpotifyEmbedType; id: string; url: string }
interface SoundCloudCustomMusic { kind: 'soundcloud'; url: string }

const TRACK_ID = '6Hv4AhlMTDgb6HGTvI0xlH';
const PLAYLIST_ID = '5wVcAsTvq2dQFZcqw3GJWN';
const EXTRA_TRACKS = ['4WZYBWngq9ODEqPB05WW7S'] as const;

function isRecord(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === 'object' && !Array.isArray(value); }
function isSpotifyType(value: unknown): value is SpotifyEmbedType { return value === 'track' || value === 'album' || value === 'playlist' || value === 'artist' || value === 'episode' || value === 'show'; }
function isCustomMusic(value: unknown): value is CustomMusic { return isRecord(value) && (value.kind === 'soundcloud' && typeof value.url === 'string' || value.kind === 'spotify' && isSpotifyType(value.type) && typeof value.id === 'string' && typeof value.url === 'string'); }
function spotifyTypeFromMatch(value: string): SpotifyEmbedType | null { return isSpotifyType(value) ? value : null; }

function ensureSpotifyAPI(callback: (api: SpotifyEmbedAPI) => void): void {
  if (window.__spotifyAPI) { callback(window.__spotifyAPI); return; }
  window.__spotifyCbs = window.__spotifyCbs ?? [];
  window.__spotifyCbs.push(callback);
  if (window.__spotifyApiLoading) return;
  window.__spotifyApiLoading = true;
  window.onSpotifyIframeApiReady = (api: SpotifyEmbedAPI) => { window.__spotifyAPI = api; (window.__spotifyCbs ?? []).forEach((fn) => { try { fn(api); } catch { /* API externa best-effort */ } }); window.__spotifyCbs = []; };
  const script = document.createElement('script'); script.src = 'https://open.spotify.com/embed/iframe-api/v1'; script.async = true; document.head.appendChild(script);
}

function plainEmbed(type: SpotifyEmbedType, id: string, height: number): HTMLIFrameElement { return h('iframe', { className: 'musica-embed', src: `https://open.spotify.com/embed/${type}/${id}`, width: '100%', height: String(height), allow: 'autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture', loading: 'lazy' }); }

function ensureSoundCloudAPI(callback: () => void): void {
  if (window.SC?.Widget) { callback(); return; }
  window.__scCbs = window.__scCbs ?? []; window.__scCbs.push(callback); if (window.__scLoading) return; window.__scLoading = true;
  const script = document.createElement('script'); script.src = 'https://w.soundcloud.com/player/api.js'; script.async = true; script.onload = () => { (window.__scCbs ?? []).forEach((fn) => { try { fn(); } catch { /* API externa best-effort */ } }); window.__scCbs = []; }; document.head.appendChild(script);
}

function soundcloudSection(): HTMLDivElement {
  const wrap = h('div', { className: 'sc-section' }); const playerHost = h('div', { className: 'sc-player' }); const nowPlaying = h('div', { className: 'sc-now u-text-muted' }, 'Clique numa faixa: ela toca e recomeça sozinha (loop) até você pausar ou escolher outra.'); let widget: SoundCloudWidget | null = null; let activeEl: HTMLButtonElement | null = null;
  function play(track: SoundCloudTrack, element: HTMLButtonElement): void { activeEl?.classList.remove('is-active'); activeEl = element; element.classList.add('is-active'); nowPlaying.textContent = `♫ Em loop: ${track.title} — ${track.artist}`; if (!widget) { const src = `https://w.soundcloud.com/player/?url=${encodeURIComponent(track.url)}&color=%2300f0ff&auto_play=true&hide_related=true&show_comments=false&show_user=true&visual=false`; const iframe = h('iframe', { className: 'sc-iframe', width: '100%', height: '140', allow: 'autoplay', frameborder: 'no', scrolling: 'no', src }); empty(playerHost); playerHost.appendChild(iframe); ensureSoundCloudAPI(() => { const api = window.SC; if (!api) return; try { widget = api.Widget(iframe); widget.bind(api.Widget.Events.FINISH, () => { try { widget?.seekTo(0); widget?.play(); } catch { /* stream externo */ } }); } catch { /* stream externo */ } }); } else { try { widget.load(track.url, { auto_play: true, color: '#d4a24e', hide_related: true, show_comments: false }); } catch { /* stream externo */ } } }
  const list = h('div', { className: 'sc-list' }); SOUNDCLOUD_TRACKS.forEach((track) => { let element!: HTMLButtonElement; element = h('button', { className: 'sc-track', type: 'button', onclick: () => play(track, element) }, track.cover ? h('img', { className: 'sc-track__cover', src: track.cover, loading: 'lazy', alt: '', referrerpolicy: 'no-referrer' }) : h('span', { className: 'sc-track__cover sc-track__cover--icon' }, '♪'), h('div', { className: 'sc-track__meta' }, h('div', { className: 'sc-track__title' }, track.title), h('div', { className: 'sc-track__artist u-text-muted' }, track.artist)), h('span', { className: 'sc-track__play' }, '▶')); list.appendChild(element); }); wrap.append(playerHost, nowPlaying, list); return wrap;
}

function parseMusicUrl(url: string): CustomMusic | null { const value = url.trim(); const match = value.match(/open\.spotify\.com\/(track|album|playlist|artist|episode|show)\/([A-Za-z0-9]+)/); if (match) { const type = spotifyTypeFromMatch(match[1]); if (type) return { kind: 'spotify', type, id: match[2], url: value }; } if (/soundcloud\.com\//i.test(value)) return { kind: 'soundcloud', url: value }; return null; }

function customTracksSection(): HTMLDivElement {
  const key = 'musicas:custom'; const inputBox = h('input', { type: 'text', placeholder: 'Cole um link do Spotify (faixa/álbum/playlist) ou SoundCloud…', style: { flex: '1', minWidth: '0', background: 'var(--color-bg-elevated)', color: 'var(--color-text-primary)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 'var(--radius-sm)', padding: '9px 12px', fontSize: 'var(--font-size-sm)' } }); const list = h('div', { style: { display: 'grid', gap: 'var(--space-md)', marginTop: 'var(--space-sm)' } });
  function load(): CustomMusic[] { const value = storage.get<unknown>(key, []); return Array.isArray(value) ? value.filter(isCustomMusic) : []; } function save(items: readonly CustomMusic[]): void { storage.set(key, items); }
  function embedFor(item: CustomMusic): HTMLIFrameElement { if (item.kind === 'spotify') return plainEmbed(item.type, item.id, item.type === 'track' ? 152 : 380); return h('iframe', { className: 'sc-iframe', width: '100%', height: '140', allow: 'autoplay', frameborder: 'no', scrolling: 'no', src: `https://w.soundcloud.com/player/?url=${encodeURIComponent(item.url)}&color=%2300f0ff&hide_related=true&show_comments=false&show_user=true` }); }
  function render(): void { empty(list); const items = load(); if (!items.length) { list.appendChild(h('p', { className: 'u-text-muted', style: { fontSize: '13px' } }, 'Nenhuma faixa sua ainda — cole um link acima e ela fica salva neste navegador.')); return; } items.forEach((item, index) => { list.appendChild(h('div', { style: { position: 'relative' } }, h('button', { title: 'Remover', onclick: () => { const current = load(); current.splice(index, 1); save(current); render(); toast('Removida'); }, style: { position: 'absolute', top: '4px', right: '4px', zIndex: '2', background: 'rgba(0,0,0,0.6)', color: '#ff5b7a', border: 'none', borderRadius: '4px', cursor: 'pointer', width: '24px', height: '24px' } }, '✕'), h('div', { className: 'musica-host' }, embedFor(item)))); }); }
  function add(): void { const parsed = parseMusicUrl(inputBox.value); if (!parsed) { toast('Cole um link válido do Spotify ou SoundCloud', { type: 'warning' }); return; } const items = load(); if (items.some((item) => item.url === parsed.url)) { toast('Essa já está na lista', { type: 'warning' }); inputBox.value = ''; return; } items.unshift(parsed); save(items); inputBox.value = ''; render(); toast('Faixa adicionada', { type: 'success' }); }
  inputBox.addEventListener('keydown', (event: KeyboardEvent) => { if (event.key === 'Enter') add(); }); const addButton = h('button', { className: 'btn btn--primary', onclick: add }, '➕ Adicionar'); const wrap = h('div', { className: 'musica-custom' }, h('div', { style: { display: 'flex', gap: 'var(--space-sm)' } }, inputBox, addButton), list); render(); return wrap;
}

function albunsSection(): HTMLDivElement {
  const grid = h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: 'var(--space-md)' } });
  ALBUNS.forEach((album: Album) => { const player = h('div', { style: { marginTop: '8px' } }); const tracks = h('div', { style: { display: 'flex', flexDirection: 'column', gap: '2px', marginTop: '8px' } }); (album.faixas ?? []).forEach((track: AlbumTrack, index: number) => { tracks.appendChild(h('button', { type: 'button', style: { display: 'flex', gap: '8px', alignItems: 'center', textAlign: 'left', background: 'transparent', border: 'none', color: 'var(--color-text-secondary)', cursor: track.url ? 'pointer' : 'default', padding: '4px 6px', borderRadius: 'var(--radius-sm)', fontSize: 'var(--font-size-sm)' }, onclick: () => { if (!track.url) return; empty(player); if (/spotify\.com/.test(track.url)) { const match = track.url.match(/(track|album|playlist)\/([A-Za-z0-9]+)/); const type = match ? spotifyTypeFromMatch(match[1]) : null; if (match && type) player.appendChild(plainEmbed(type, match[2], 80)); } else player.appendChild(h('iframe', { className: 'sc-iframe', width: '100%', height: '120', allow: 'autoplay', frameborder: 'no', scrolling: 'no', src: `https://w.soundcloud.com/player/?url=${encodeURIComponent(track.url)}&color=%2300f0ff&auto_play=true&hide_related=true&show_comments=false` })); } }, h('span', { className: 'u-mono u-text-muted', style: { width: '18px' } }, String(index + 1)), h('span', null, track.titulo))); }); grid.appendChild(h('div', { className: 'card', style: { padding: 'var(--space-md)' } }, h('div', { style: { display: 'flex', gap: '12px' } }, album.capa ? h('img', { src: album.capa, loading: 'lazy', referrerpolicy: 'no-referrer', alt: '', style: { width: '88px', height: '88px', objectFit: 'cover', borderRadius: 'var(--radius-sm)', flexShrink: '0' } }) : h('div', { style: { width: '88px', height: '88px', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--color-bg-elevated)', borderRadius: 'var(--radius-sm)', fontSize: '28px' } }, '♪'), h('div', null, h('div', { style: { fontWeight: '700', color: 'var(--color-text-primary)' } }, album.titulo), h('div', { className: 'u-text-muted', style: { fontSize: 'var(--font-size-sm)' } }, album.artista), h('div', { className: 'u-text-muted', style: { fontSize: '12px' } }, String(album.ano)))), tracks, player)); }); return grid;
}

function meuAcervoSection(): HTMLDivElement {
  const wrap = h('div', { className: 'acervo' }); if (!offlineAudioSupported()) { wrap.appendChild(h('p', { className: 'u-text-muted' }, 'Seu navegador não suporta o armazenamento offline (IndexedDB) usado pelo acervo.')); return wrap; }
  let tracks: OfflineTrack[] = []; let currentId: string | null = null; let currentUrl: string | null = null; const savedLoop = storage.get<boolean>('musicas:acervoLoop', true); let loopAll = savedLoop !== false;
  const audio = h('audio', { className: 'acervo__audio', controls: true, preload: 'metadata' }); const listEl = h('div', { className: 'acervo__list' }); const statsEl = h('div', { className: 'acervo__stats u-text-muted' });
  function indexOfCurrent(): number { return tracks.findIndex((track) => track.id === currentId); } function markActive(): void { listEl.querySelectorAll<HTMLElement>('.acervo__track').forEach((element) => element.classList.toggle('is-active', element.dataset.id === currentId)); }
  async function play(id: string): Promise<void> { const blob = await getBlob(id); if (!blob) { toast('Faixa não encontrada no acervo', { type: 'warning' }); await refresh(); return; } if (currentUrl) URL.revokeObjectURL(currentUrl); currentUrl = URL.createObjectURL(blob); currentId = id; audio.src = currentUrl; loadBookmark(`musica:acervo/${id}`).then((bookmark) => { if (!bookmark || currentId !== id) return; const position = Number(bookmark.position_secs) || 0; const seek = (): void => { if (position > 5 && (!audio.duration || position < audio.duration - 10)) audio.currentTime = position; }; if (audio.readyState >= 1) seek(); else audio.addEventListener('loadedmetadata', seek, { once: true }); }).catch(() => { /* bookmark é best-effort */ }); void audio.play().catch(() => undefined); markActive(); }
  audio.addEventListener('timeupdate', () => { if (!currentId || !audio.duration || audio.paused) return; const track = tracks.find((item) => item.id === currentId); const meta: Record<string, unknown> = { name: track?.name ?? 'faixa' }; saveBookmark(`musica:acervo/${currentId}`, { kind: 'musica', position: audio.currentTime, duration: audio.duration, meta }); });
  function playAt(offset: number): void { if (!tracks.length) return; const index = indexOfCurrent(); let next = (index < 0 ? -1 : index) + offset; if (next >= tracks.length) { if (!loopAll) return; next = 0; } if (next < 0) next = loopAll ? tracks.length - 1 : 0; void play(tracks[next].id); }
  audio.addEventListener('ended', () => playAt(1));
  const fileInput = h('input', { type: 'file', accept: 'audio/*', multiple: true, style: { display: 'none' }, onchange: (event: Event) => { if (!(event.target instanceof HTMLInputElement)) return; void ingest(event.target.files); event.target.value = ''; } }); const addButton = h('button', { className: 'btn btn--primary', onclick: () => fileInput.click() }, '➕ Adicionar músicas');
  async function ingest(files: FileList | null): Promise<void> { if (!files) return; const added = await addFiles(files); if (!added.length) { toast('Selecione arquivos de áudio (mp3, m4a, ogg, wav…)', { type: 'warning' }); return; } toast(`${added.length} faixa(s) adicionada(s) ao acervo`, { type: 'success' }); await refresh(); }
  const drop = h('div', { className: 'acervo__drop', ondragover: (event: DragEvent) => { event.preventDefault(); drop.classList.add('is-drag'); }, ondragleave: () => drop.classList.remove('is-drag'), ondrop: (event: DragEvent) => { event.preventDefault(); drop.classList.remove('is-drag'); void ingest(event.dataTransfer?.files ?? null); } }, h('span', { className: 'acervo__drop-ico' }, '🎧'), h('div', { className: 'acervo__drop-text' }, h('strong', null, 'Arraste seus arquivos de áudio aqui'), h('div', { className: 'u-text-muted', style: { fontSize: '13px' } }, 'ou clique para escolher. Ficam guardados só neste aparelho e tocam ', h('span', { className: 'u-text-cyan' }, 'offline, em qualquer rede'), ' — não dependem de Spotify/YouTube.')), addButton);
  const prevButton = h('button', { className: 'btn btn--ghost', title: 'Anterior', onclick: () => playAt(-1) }, '⏮'); const nextButton = h('button', { className: 'btn btn--ghost', title: 'Próxima', onclick: () => playAt(1) }, '⏭'); const loopButton = h('button', { className: cx('btn', 'btn--ghost', 'acervo__loop', loopAll && 'is-on'), title: 'Repetir a lista', onclick: () => { loopAll = !loopAll; storage.set('musicas:acervoLoop', loopAll); loopButton.classList.toggle('is-on', loopAll); toast(loopAll ? 'Repetir lista: ligado' : 'Repetir lista: desligado'); } }, '🔁 Repetir');
  const clearButton = h('button', { className: 'btn btn--ghost', title: 'Remover todas', onclick: () => { if (!tracks.length || !window.confirm('Remover TODAS as músicas do acervo offline deste aparelho?')) return; void (async () => { await clearAll(); audio.pause(); audio.removeAttribute('src'); currentId = null; if (currentUrl) { URL.revokeObjectURL(currentUrl); currentUrl = null; } await refresh(); toast('Acervo limpo'); })(); } }, '🗑 Limpar');
  function renderList(): void { empty(listEl); if (!tracks.length) { listEl.appendChild(h('p', { className: 'u-text-muted', style: { fontSize: '13px', padding: '4px 2px' } }, 'Acervo vazio — adicione suas músicas acima e elas ficam aqui pra tocar offline.')); return; } tracks.forEach((track, index) => { listEl.appendChild(h('div', { className: 'acervo__track', dataset: { id: track.id } }, h('button', { className: 'acervo__play', title: 'Tocar', onclick: () => void play(track.id) }, '▶'), h('span', { className: 'acervo__num u-mono' }, String(index + 1).padStart(2, '0')), h('div', { className: 'acervo__meta' }, h('div', { className: 'acervo__title' }, track.name), h('div', { className: 'acervo__sub u-text-muted' }, formatSize(track.size))), h('button', { className: 'acervo__rm', title: 'Remover', onclick: () => { void (async () => { await removeTrack(track.id); if (currentId === track.id) { audio.pause(); currentId = null; } await refresh(); toast('Removida'); })(); } }, '✕'))); }); markActive(); }
  function renderStats(): void { const total = tracks.reduce((sum, track) => sum + track.size, 0); statsEl.textContent = tracks.length ? `${tracks.length} faixa(s) · ${formatSize(total)} no aparelho · tocam offline, em qualquer rede` : ''; }
  async function refresh(): Promise<void> { tracks = await listTracks(); renderList(); renderStats(); }
  wrap.append(drop, fileInput, h('div', { className: 'acervo__bar' }, prevButton, nextButton, loopButton, h('span', { style: { flex: '1' } }), clearButton), audio, listEl, statsEl); void refresh(); return wrap;
}

function musicasPropriasSection(): HTMLDivElement {
  const wrap = h('div', { className: 'proprias' }); const player = h('div', { className: 'proprias__player' }); let ativa: string | null = null;
  function tocar(music: MusicaPropria, button: HTMLButtonElement): void { empty(player); if (ativa === music.uid) { ativa = null; button.classList.remove('is-on'); return; } ativa = music.uid; wrap.querySelectorAll<HTMLButtonElement>('.proprias__faixa').forEach((element) => element.classList.remove('is-on')); button.classList.add('is-on'); player.append(h('iframe', { className: 'proprias__frame', src: music.embed, title: music.titulo, allow: 'autoplay; encrypted-media; fullscreen', loading: 'eager', frameborder: '0' }), h('p', { className: 'proprias__credito u-text-muted' }, '♪ ', h('a', { href: music.url, target: '_blank', rel: 'noopener noreferrer' }, music.titulo), ' — criada pelo operador no ', h('a', { href: SUNO_PERFIL, target: '_blank', rel: 'noopener noreferrer' }, 'Suno AI'))); player.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }
  const grade = h('div', { className: 'proprias__grade' }, ...MUSICAS_PROPRIAS.map((music: MusicaPropria) => { let button!: HTMLButtonElement; button = h('button', { className: 'proprias__faixa', onclick: () => tocar(music, button) }, music.capa ? h('img', { className: 'proprias__capa', src: music.capa, alt: music.titulo, loading: 'lazy' }) : h('span', { className: 'proprias__capa proprias__capa--vazia' }, '♪'), h('span', { className: 'proprias__rotulo' }, h('span', { className: 'proprias__num' }, String(music.n).padStart(2, '0')), h('span', { className: 'proprias__nome' }, 'A Baluarte'))); return button; }));
  const locais = MUSICAS_LOCAIS.length ? h('div', { className: 'proprias__locais' }, ...MUSICAS_LOCAIS.map((music: MusicaLocal) => h('div', { className: 'proprias__local' }, h('span', { className: 'proprias__local-nome' }, '🎻 ', music.titulo), h('audio', { controls: true, preload: 'none', src: music.arquivo })))) : null;
  wrap.append(h('p', { className: 'musica-nota u-text-muted' }, '🎤 Composições do próprio operador (Suno AI) — a obra "A Baluarte" em ', String(MUSICAS_PROPRIAS.length), ' variações. Clique numa capa pra tocar aqui.'), grade, player); if (locais) wrap.append(locais); return wrap;
}

export function musicasPage(): HTMLDivElement {
  const fullPage = h('div', { className: 'page-musicas' }); fullPage.appendChild(buildImmersiveHero({ kicker: 'BALUARTE · MÍDIA · MÚSICA', title: 'Central de Música', sub: 'PLAYLIST & LOOP', desc: ['Comece pelo ', h('span', { className: 'u-text-cyan' }, 'Meu Acervo'), ' — suas músicas tocam offline, em qualquer rede. Abaixo, a faixa em ', h('span', { className: 'u-text-cyan' }, 'loop infinito'), ' e a playlist completa via Spotify.'], hudLeft: '♪ ÁUDIO', hudRight: 'OFFLINE · SPOTIFY' }));
  fullPage.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, '🎧 Meu Acervo'), h('span', { className: 'acervo-badge' }, 'offline · qualquer rede'))); fullPage.appendChild(meuAcervoSection());
  fullPage.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, '🎤 Músicas Próprias'), h('span', { className: 'section-header__count' }, String(MUSICAS_PROPRIAS.length)))); fullPage.appendChild(musicasPropriasSection());
  fullPage.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, '◆ Faixa em Destaque')));
  const trackHost = h('div', { className: 'musica-host' }); let fellBack = false; const fallbackTimer = window.setTimeout(() => { if (!trackHost.firstChild) { fellBack = true; trackHost.appendChild(plainEmbed('track', TRACK_ID, 152)); } }, 5000);
  ensureSpotifyAPI((api) => { if (fellBack) return; window.clearTimeout(fallbackTimer); try { api.createController(trackHost, { uri: `spotify:track:${TRACK_ID}`, width: '100%', height: 152 }, (controller: SpotifyController) => { let cooldown = false; controller.addListener('playback_update', (event) => { const data = event.data; if (!data?.duration || data.position === undefined) return; if (!cooldown && data.position >= data.duration - 900) { cooldown = true; try { if (controller.restart) controller.restart(); else { controller.seek(0); controller.play(); } } catch { /* player externo */ } window.setTimeout(() => { cooldown = false; }, 2500); } }); }); } catch { if (!trackHost.firstChild) trackHost.appendChild(plainEmbed('track', TRACK_ID, 152)); } });
  fullPage.appendChild(trackHost); fullPage.appendChild(h('p', { className: 'musica-nota u-text-muted' }, '↻ Em loop: ao chegar ao fim, a faixa recomeça sozinha enquanto você estiver nesta aba. Se o player não tocar a faixa inteira, é limite do Spotify para quem não está logado.'));
  if (ALBUNS.length) { fullPage.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, '💿 Álbuns'), h('span', { className: 'section-header__count' }, String(ALBUNS.length)))); fullPage.appendChild(albunsSection()); }
  fullPage.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, '➕ Suas Faixas'))); fullPage.appendChild(customTracksSection());
  fullPage.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, '♫ SoundCloud — Minhas Faixas'), h('span', { className: 'section-header__count' }, String(SOUNDCLOUD_TRACKS.length)))); fullPage.appendChild(soundcloudSection());
  if (EXTRA_TRACKS.length) { fullPage.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, '♫ Músicas'))); const grid = h('div', { className: 'musica-grid' }); EXTRA_TRACKS.forEach((id) => grid.appendChild(h('div', { className: 'musica-host' }, plainEmbed('track', id, 152)))); fullPage.appendChild(grid); }
  fullPage.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, '◫ Playlist'))); fullPage.appendChild(h('div', { className: 'musica-host' }, plainEmbed('playlist', PLAYLIST_ID, 420))); return fullPage;
}
