import '../styles/radar.css';
import { h, cx, empty } from '../utils/helpers.js';
import { aoSair } from '../core/ciclo-vida.js';
import { makeSource } from '../utils/radar-source.js';
import type { RadarFrame, RadarMode, RadarSource } from '../utils/radar-source.js';
import { cfar2d, rangeMeters, velocityMs } from '../utils/radar-dsp.js';
import type { RadarTrack } from '../utils/radar-tracker.js';
import { createTracker } from '../utils/radar-tracker.js';
import { toast } from '../utils/toast';

type ConsoleMode = RadarMode | 'satellite';
interface RadarConfig { cfarK: number; mtiOn: boolean; dcNotchOn: boolean; frozen: boolean }
interface SatelliteRecord { readonly name: string; readonly satrec: unknown }
interface SatelliteApi {
  twoline2satrec(line1: string, line2: string): unknown;
  gstime(date: Date): number;
  propagate(satrec: unknown, date: Date): { position?: { x: number; y: number; z: number } };
  eciToEcf(position: { x: number; y: number; z: number }, gmst: number): unknown;
  ecfToLookAngles(observer: { latitude: number; longitude: number; height: number }, ecf: unknown): { elevation: number; azimuth: number; rangeSat: number };
}
declare global { interface Window { satellite?: SatelliteApi } }

let source: RadarSource | null = null;
let mode: ConsoleMode = 'mock';
const config: RadarConfig = { cfarK: 4, mtiOn: false, dcNotchOn: true, frozen: false };
let lastFrame: RadarFrame | null = null;
let previousMagnitude: Float32Array | null = null;
let fpsCounter = { count: 0, last: performance.now(), value: 0 };
let tracker = createTracker();
let tracksCache: RadarTrack[] = [];
let rangeDopplerCanvas: HTMLCanvasElement | null = null;
let waterfallCanvas: HTMLCanvasElement | null = null;
let detectionList: HTMLDivElement | null = null;
let statusBar: HTMLDivElement | null = null;
let modeButtons: HTMLDivElement | null = null;
let freezeButton: HTMLButtonElement | null = null;
let rangeMain: HTMLDivElement | null = null;
let satelliteCanvas: HTMLCanvasElement | null = null;
let satelliteLibrary: SatelliteApi | null = null;
let satelliteTles: SatelliteRecord[] = [];
let satelliteTimer: number | null = null;
let observerPosition = { lat: -15.8, lon: -47.9, alt: 0 };

const PALETTE = buildPalette();

function loadSatelliteLibrary(): Promise<SatelliteApi | null> {
  return new Promise((resolve) => {
    if (window.satellite) { resolve(window.satellite); return; }
    const script = document.createElement('script'); script.src = 'https://cdn.jsdelivr.net/npm/satellite.js@5.0.0/dist/satellite.min.js'; script.onload = () => resolve(window.satellite ?? null); script.onerror = () => resolve(null); document.head.appendChild(script);
  });
}
async function fetchTle(): Promise<unknown[]> { const response = await fetch('https://celestrak.org/gp/query?GROUP=visual&FORMAT=JSON', { signal: AbortSignal.timeout(14000) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data: unknown = await response.json(); return Array.isArray(data) ? data : []; }
function record(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === 'object' && !Array.isArray(value); }
async function initSatelliteMode(): Promise<void> {
  setStatus('link', 'carregando…'); setStatus('mode', 'SATÉLITE');
  if (navigator.geolocation) navigator.geolocation.getCurrentPosition((position) => { observerPosition = { lat: position.coords.latitude, lon: position.coords.longitude, alt: (position.coords.altitude ?? 0) / 1000 }; }, () => {});
  satelliteLibrary = await loadSatelliteLibrary(); if (!satelliteLibrary) { toast('Falha ao carregar satellite.js', { type: 'warning' }); setStatus('link', 'ERRO'); return; }
  try { satelliteTles = (await fetchTle()).flatMap((item) => { if (!record(item) || typeof item.TLE_LINE1 !== 'string' || typeof item.TLE_LINE2 !== 'string') return []; try { return [{ name: String(item.OBJECT_NAME ?? item.name ?? '???').trim(), satrec: satelliteLibrary?.twoline2satrec(item.TLE_LINE1, item.TLE_LINE2) }]; } catch { return []; } }); setStatus('link', 'LIVE'); toast(`${satelliteTles.length} satélites carregados (CelesTrak)`, { type: 'success' }); } catch { toast('Falha ao buscar TLEs da CelesTrak. Verifique a conexão.', { type: 'warning' }); setStatus('link', 'OFFLINE'); return; }
  const loop = (): void => { if (mode !== 'satellite') return; drawSatelliteScope(); satelliteTimer = window.setTimeout(loop, 2000); }; loop();
}
function stopSatelliteMode(): void { if (satelliteTimer !== null) { window.clearTimeout(satelliteTimer); satelliteTimer = null; } }
function drawSatelliteScope(): void {
  if (!satelliteCanvas || !satelliteLibrary || !satelliteTles.length) return; const context = satelliteCanvas.getContext('2d'); if (!context) return;
  const width = satelliteCanvas.width; const height = satelliteCanvas.height; const centerX = width / 2; const centerY = height / 2; const radius = Math.min(centerX, centerY) - 28;
  context.fillStyle = '#020409'; context.fillRect(0, 0, width, height);
  const elevationRadius = (elevation: number): number => radius * (1 - elevation / 90);
  context.strokeStyle = 'rgba(212,162,78,0.12)'; context.lineWidth = 1; [0, 30, 60].forEach((elevation) => { context.beginPath(); context.arc(centerX, centerY, elevationRadius(elevation), 0, Math.PI * 2); context.stroke(); context.fillStyle = 'rgba(212,162,78,0.35)'; context.font = '9px "JetBrains Mono",monospace'; context.textAlign = 'left'; context.textBaseline = 'middle'; context.fillText(`${elevation}°`, centerX + elevationRadius(elevation) + 3, centerY); });
  context.strokeStyle = 'rgba(212,162,78,0.1)'; context.beginPath(); context.moveTo(centerX, centerY - radius); context.lineTo(centerX, centerY + radius); context.moveTo(centerX - radius, centerY); context.lineTo(centerX + radius, centerY); context.stroke(); context.fillStyle = '#d4a24e'; context.font = 'bold 10px "JetBrains Mono",monospace'; context.textAlign = 'center'; context.textBaseline = 'middle'; [['N', 0], ['L', 90], ['S', 180], ['O', 270]].forEach(([label, azimuth]) => { const radian = (Number(azimuth) - 90) * Math.PI / 180; context.fillText(String(label), centerX + (radius + 16) * Math.cos(radian), centerY + (radius + 16) * Math.sin(radian)); });
  const now = new Date(); const gmst = satelliteLibrary.gstime(now); const observer = { latitude: observerPosition.lat * Math.PI / 180, longitude: observerPosition.lon * Math.PI / 180, height: observerPosition.alt }; const visible: Array<{ name: string; elevation: number; azimuth: number; range: number }> = [];
  satelliteTles.forEach(({ name, satrec }) => { try { const position = satelliteLibrary?.propagate(satrec, now).position; if (!position || !satelliteLibrary) return; const look = satelliteLibrary.ecfToLookAngles(observer, satelliteLibrary.eciToEcf(position, gmst)); const elevation = look.elevation * 180 / Math.PI; if (elevation >= 0) visible.push({ name, elevation, azimuth: look.azimuth * 180 / Math.PI, range: look.rangeSat }); } catch { /* TLE individual inválido */ } });
  visible.sort((a, b) => b.elevation - a.elevation); setStatus('tgt', String(visible.length)); visible.forEach(({ name, elevation, azimuth }, index) => { const radial = elevationRadius(elevation); const angle = (azimuth - 90) * Math.PI / 180; const x = centerX + radial * Math.cos(angle); const y = centerY + radial * Math.sin(angle); const highlight = elevation > 60; context.fillStyle = highlight ? '#e8c07a' : '#d4a24e'; context.beginPath(); context.arc(x, y, highlight ? 4 : 2.5, 0, Math.PI * 2); context.fill(); if (index < 10 || highlight) { context.fillStyle = highlight ? '#e8c07a' : 'rgba(212,162,78,0.75)'; context.font = '9px "JetBrains Mono",monospace'; context.textAlign = 'left'; context.textBaseline = 'top'; context.fillText(name.slice(0, 14), x + 6, y - 3); } });
  context.fillStyle = '#ffffff88'; context.beginPath(); context.arc(centerX, centerY, 3, 0, Math.PI * 2); context.fill(); context.fillStyle = 'rgba(212,162,78,0.5)'; context.font = '9px "JetBrains Mono",monospace'; context.textAlign = 'left'; context.textBaseline = 'top'; context.fillText(`OBS ${observerPosition.lat.toFixed(1)}°, ${observerPosition.lon.toFixed(1)}°`, 6, 6); context.fillText(now.toLocaleTimeString('pt-BR'), 6, 18);
  if (!detectionList) return; const list = detectionList; empty(list); if (!visible.length) { list.appendChild(h('div', { className: 'u-text-muted u-mono' }, 'nenhum satélite acima do horizonte')); return; } visible.slice(0, 15).forEach(({ name, elevation, azimuth, range }) => list.appendChild(h('div', { className: 'rdr-det-row' }, h('span', { className: 'rdr-det-row__id u-mono', style: 'max-width:90px;overflow:hidden' }, name.slice(0, 10)), h('span', { className: 'rdr-det-row__range u-mono' }, `El ${elevation.toFixed(0)}°`), h('span', { className: 'rdr-det-row__vel u-mono' }, `Az ${azimuth.toFixed(0)}°`), h('span', { className: 'rdr-det-row__snr u-mono u-text-cyan' }, `${Math.round(range)} km`))));
}

function buildSensorSources(): HTMLDivElement {
  const sensors = [{ icon: '👁️', name: 'Óptico / Térmico + IA', rota: '/visao', desc: 'Câmera com detecção e rastreio por visão computacional.' }, { icon: '🛰️', name: 'Satélites (orbital)', rota: '/radar', desc: 'TLE do CelesTrak — modo Satélites deste console.' }, { icon: '🧭', name: 'Geo / Posição', rota: '/geo', desc: 'GeoPulse e localização do operador.' }, { icon: '🔐', name: 'RF passivo / SIGINT', rota: '/ciberseg', desc: 'Escuta de emissões e ameaças.' }, { icon: '📡', name: 'Triangulação', rota: '/triangulacao', desc: 'Localização por múltiplos pontos.' }, { icon: '🚀', name: 'Doutrina de sensores', rota: '/tecnologia-militar', desc: 'Referência: SAR, LIDAR, acústico, sísmico.' }]; const grid = h('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: '8px', marginTop: '8px' } }); sensors.forEach((sensor) => grid.appendChild(h('a', { href: `#${sensor.rota}`, style: { display: 'flex', gap: '8px', alignItems: 'flex-start', padding: '8px 10px', borderRadius: 'var(--radius-sm)', background: 'var(--color-bg-elevated)', border: '1px solid rgba(255,255,255,0.07)', color: 'inherit', textDecoration: 'none' } }, h('span', { style: { fontSize: '18px' } }, sensor.icon), h('div', null, h('div', { style: { fontWeight: '600', fontSize: 'var(--font-size-sm)' } }, sensor.name), h('div', { className: 'u-text-muted', style: { fontSize: '12px' } }, sensor.desc))))); return h('div', { className: 'card', style: { marginTop: 'var(--space-md)' } }, h('h3', { style: { margin: '0 0 4px' } }, '📡 Fontes de Detecção · fusão multi-sensor'), h('p', { className: 'u-text-muted', style: { fontSize: '13px', margin: '0 0 4px' } }, 'O radar não depende de uma antena dedicada: o panorama tático é montado por fusão de sensores — cada fonte abaixo alimenta a imagem. (issue #183)'), grid);
}
function buildHeader(): HTMLDivElement { return h('div', { className: 'page-header anim-fade-in' }, h('div', { className: 'page-header__crumbs' }, h('span', null, 'BALUARTE'), h('span', null, '›'), h('span', null, 'TÁTICO'), h('span', null, '›'), h('span', null, 'RADAR')), h('h1', { className: 'page-header__title' }, '⌖ Radar Tático'), h('p', { className: 'page-header__description' }, 'Console range-Doppler com CFAR. ', h('span', { className: 'u-text-cyan' }, 'Modo ACÚSTICO funciona no celular'), ' (microfone + alto-falante, efeito Doppler). Mock roda sem nada; replay e bridge usam fixture ou WebSocket local.')); }
function buildConsole(): HTMLDivElement {
  modeButtons = h('div', { className: 'rdr-modes' }, modeButton('mock', 'MOCK'), modeButton('acoustic', '🎙 ACÚSTICO'), modeButton('passive', 'PASSIVO'), modeButton('replay', 'REPLAY'), modeButton('bridge', 'BRIDGE'), modeButton('satellite', '🛰 SATÉLITE'));
  const cfarSlider = h('input', { type: 'range', min: 2, max: 10, step: 0.1, value: config.cfarK, className: 'rdr-slider', 'aria-label': 'Fator K do detector CFAR', oninput: (event: Event) => { if (event.target instanceof HTMLInputElement) { config.cfarK = Number.parseFloat(event.target.value); const label = event.target.parentElement?.querySelector('.rdr-slider__val'); if (label) label.textContent = config.cfarK.toFixed(1); } } });
  const mtiToggle = toggle('MTI', config.mtiOn, (value) => { config.mtiOn = value; }); const dcToggle = toggle('DC notch', config.dcNotchOn, (value) => { config.dcNotchOn = value; });
  freezeButton = h('button', { className: 'btn btn--ghost rdr-freeze', onclick: () => { config.frozen = !config.frozen; freezeButton?.classList.toggle('is-active', config.frozen); if (freezeButton) freezeButton.textContent = config.frozen ? '▶ RETOMAR' : '⏸ FREEZE'; } }, '⏸ FREEZE');
  const controls = h('div', { className: 'rdr-controls card' }, h('div', { className: 'rdr-controls__row' }, h('span', { className: 'rdr-controls__label' }, 'FONTE'), modeButtons), h('div', { className: 'rdr-controls__row' }, h('span', { className: 'rdr-controls__label' }, 'CFAR k'), h('div', { className: 'rdr-slider-wrap' }, cfarSlider, h('span', { className: 'rdr-slider__val u-mono' }, config.cfarK.toFixed(1)))), h('div', { className: 'rdr-controls__row' }, mtiToggle, dcToggle, freezeButton));
  statusBar = h('div', { className: 'rdr-status' }, statusItem('MODE', 'MOCK', 'mode'), statusItem('FPS', '0', 'fps'), statusItem('TGT', '0', 'tgt'), statusItem('FRAME', '0', 'frame'), statusItem('LINK', '─', 'link'));
  rangeDopplerCanvas = h('canvas', { className: 'rdr-rd', width: 512, height: 320 }); waterfallCanvas = h('canvas', { className: 'rdr-waterfall', width: 512, height: 160 }); satelliteCanvas = h('canvas', { className: 'rdr-sat-scope', width: 512, height: 480, style: 'display:none' });
  const rangeScope = h('div', { className: 'rdr-scope card' }, h('div', { className: 'rdr-scope__head' }, h('div', { className: 'rdr-scope__title' }, '⌖ RANGE × DOPPLER'), h('div', { className: 'rdr-scope__legend u-mono u-text-muted' }, 'X: velocidade · Y: alcance · brilho: magnitude')), rangeDopplerCanvas); const waterfallScope = h('div', { className: 'rdr-scope card' }, h('div', { className: 'rdr-scope__head' }, h('div', { className: 'rdr-scope__title' }, '∿ WATERFALL'), h('div', { className: 'rdr-scope__legend u-mono u-text-muted' }, 'tempo desce · range no eixo X')), waterfallCanvas); const satelliteScope = h('div', { className: 'rdr-scope card', id: 'sat-scope-card', style: 'display:none' }, h('div', { className: 'rdr-scope__head' }, h('div', { className: 'rdr-scope__title' }, '🛰 RADAR DE SATÉLITES'), h('div', { className: 'rdr-scope__legend u-mono u-text-muted' }, 'AZ/EL da sua posição · centro=zênite · borda=horizonte')), satelliteCanvas);
  detectionList = h('div', { className: 'rdr-det-list' }, h('div', { className: 'u-text-muted u-mono' }, 'sem alvos')); const detections = h('div', { className: 'rdr-det card' }, h('div', { className: 'rdr-scope__head' }, h('div', { className: 'rdr-scope__title' }, '◎ DETECÇÕES'), h('div', { className: 'rdr-scope__legend u-mono u-text-muted' }, 'CFAR-CA · ordenado por SNR')), detectionList); rangeMain = h('div', { className: 'rdr-main' }, rangeScope, waterfallScope, satelliteScope); return h('div', { className: 'rdr-layout' }, h('div', { className: 'rdr-side' }, statusBar, controls, detections), rangeMain);
}
function modeButton(kind: ConsoleMode, label: string): HTMLButtonElement { return h('button', { className: cx('rdr-mode', kind === mode && 'is-active'), 'data-kind': kind, onclick: () => { void switchSource(kind); } }, label); }
function toggle(label: string, initial: boolean, onChange: (value: boolean) => void): HTMLButtonElement { let enabled = initial; const button = h('button', { className: cx('rdr-toggle', enabled && 'is-on'), onclick: () => { enabled = !enabled; button.classList.toggle('is-on', enabled); onChange(enabled); } }, label); return button; }
function statusItem(label: string, value: string, key: string): HTMLDivElement { return h('div', { className: 'rdr-status__item', 'data-key': key }, h('span', { className: 'rdr-status__label' }, label), h('span', { className: 'rdr-status__val u-mono' }, value)); }
function setStatus(key: string, value: string): void { const item = statusBar?.querySelector(`[data-key="${key}"] .rdr-status__val`); if (item) item.textContent = value; }
async function switchSource(next: ConsoleMode): Promise<void> {
  if (mode === 'satellite' && next !== 'satellite') { stopSatelliteMode(); if (rangeDopplerCanvas?.parentElement) rangeDopplerCanvas.parentElement.style.display = ''; if (waterfallCanvas?.parentElement) waterfallCanvas.parentElement.style.display = ''; document.getElementById('sat-scope-card')?.style.setProperty('display', 'none'); }
  source?.stop(); source = null; tracker.reset(); tracksCache = []; mode = next; modeButtons?.querySelectorAll('.rdr-mode').forEach((button) => { if (button instanceof HTMLElement) button.classList.toggle('is-active', button.dataset.kind === next); });
  if (next === 'satellite') { if (rangeDopplerCanvas?.parentElement) rangeDopplerCanvas.parentElement.style.display = 'none'; if (waterfallCanvas?.parentElement) waterfallCanvas.parentElement.style.display = 'none'; document.getElementById('sat-scope-card')?.style.setProperty('display', ''); await initSatelliteMode(); return; }
  setStatus('mode', next.toUpperCase()); setStatus('link', next === 'bridge' ? 'conectando…' : next === 'acoustic' ? 'iniciando…' : '─'); source = makeSource(next, { onError: (message) => { toast(message, { type: 'warning' }); setStatus('link', 'OFFLINE'); } }); void source.start(onFrame);
  if (next === 'bridge' || next === 'acoustic') window.setTimeout(() => { if (source?.kind === next) { setStatus('link', source.connected ? 'LIVE' : 'OFFLINE'); if (source.connected && next === 'acoustic') toast('Radar acústico ativo. Mexa a mão perto do aparelho.', { type: 'success' }); if (!source.connected && next === 'bridge') toast('Bridge offline. Rode tools/radar-bridge/bridge.py.', { type: 'warning' }); } }, next === 'bridge' ? 1500 : 1200);
}
function onFrame(frame: RadarFrame): void {
  if (config.frozen) return; lastFrame = frame; const magnitude = new Float32Array(frame.mag); if (config.dcNotchOn) for (let row = 0; row < frame.rows; row += 1) { let sum = 0; for (let col = 0; col < frame.cols; col += 1) sum += magnitude[row * frame.cols + col]; const mean = sum / frame.cols; for (let col = 0; col < frame.cols; col += 1) magnitude[row * frame.cols + col] = Math.max(0, magnitude[row * frame.cols + col] - mean); } if (config.mtiOn && previousMagnitude?.length === magnitude.length) for (let index = 0; index < magnitude.length; index += 1) magnitude[index] = Math.abs(magnitude[index] - previousMagnitude[index]); previousMagnitude = new Float32Array(magnitude); const cfar = cfar2d(magnitude, frame.rows, frame.cols, { guard: 1, ref: 3, k: config.cfarK }); tracksCache = tracker.update(cfar.detections); drawRangeDoppler(magnitude, frame.rows, frame.cols, cfar.mask); drawTrackOverlay(tracksCache, frame.rows, frame.cols); shiftWaterfall(magnitude, frame.rows, frame.cols); renderDetections(); fpsCounter.count += 1; const now = performance.now(); if (now - fpsCounter.last >= 1000) { fpsCounter.value = Math.round(fpsCounter.count * 1000 / (now - fpsCounter.last)); fpsCounter.count = 0; fpsCounter.last = now; setStatus('fps', String(fpsCounter.value)); } setStatus('tgt', String(tracksCache.length)); setStatus('frame', String(frame.index));
}
function buildPalette(): Uint8ClampedArray { const palette = new Uint8ClampedArray(256 * 4); for (let index = 0; index < 256; index += 1) { const t = index / 255; palette[index * 4] = Math.round(255 * t ** 1.3 * (0.6 + 0.4 * t)); palette[index * 4 + 1] = Math.round(255 * t * (1 - 0.4 * t)); palette[index * 4 + 2] = Math.round(255 * (1 - (1 - t) ** 2)); palette[index * 4 + 3] = 255; } return palette; }
function drawRangeDoppler(magnitude: Float32Array, rows: number, cols: number, mask: Uint8Array): void { if (!rangeDopplerCanvas) return; const context = rangeDopplerCanvas.getContext('2d'); if (!context) return; const width = rangeDopplerCanvas.width; const height = rangeDopplerCanvas.height; let max = 1e-6; magnitude.forEach((value) => { if (value > max) max = value; }); const cellWidth = width / cols; const cellHeight = height / rows; context.fillStyle = '#020409'; context.fillRect(0, 0, width, height); for (let row = 0; row < rows; row += 1) for (let col = 0; col < cols; col += 1) { const value = Math.min(255, Math.round(magnitude[row * cols + col] / max * 255)); const offset = value * 4; context.fillStyle = `rgb(${PALETTE[offset]},${PALETTE[offset + 1]},${PALETTE[offset + 2]})`; context.fillRect(col * cellWidth, row * cellHeight, cellWidth + 0.5, cellHeight + 0.5); } context.strokeStyle = '#d4a24e'; context.lineWidth = 1.2; for (let row = 0; row < rows; row += 1) for (let col = 0; col < cols; col += 1) if (mask[row * cols + col]) context.strokeRect(col * cellWidth, row * cellHeight, cellWidth, cellHeight); context.strokeStyle = 'rgba(150, 180, 255, 0.08)'; context.lineWidth = 1; for (let index = 1; index < 8; index += 1) { const x = width / 8 * index; context.beginPath(); context.moveTo(x, 0); context.lineTo(x, height); context.stroke(); } for (let index = 1; index < 4; index += 1) { const y = height / 4 * index; context.beginPath(); context.moveTo(0, y); context.lineTo(width, y); context.stroke(); } }
function shiftWaterfall(magnitude: Float32Array, rows: number, cols: number): void { if (!waterfallCanvas) return; const context = waterfallCanvas.getContext('2d'); if (!context) return; const width = waterfallCanvas.width; const height = waterfallCanvas.height; const image = context.getImageData(0, 0, width, height - 1); context.putImageData(image, 0, 1); let max = 1e-6; const line = new Float32Array(rows); for (let row = 0; row < rows; row += 1) { for (let col = 0; col < cols; col += 1) line[row] += magnitude[row * cols + col]; if (line[row] > max) max = line[row]; } const pixelWidth = width / rows; for (let row = 0; row < rows; row += 1) { const value = Math.min(255, Math.round(line[row] / max * 255)); const offset = value * 4; context.fillStyle = `rgb(${PALETTE[offset]},${PALETTE[offset + 1]},${PALETTE[offset + 2]})`; context.fillRect(row * pixelWidth, 0, pixelWidth + 0.5, 1); } }
function drawTrackOverlay(tracks: readonly RadarTrack[], rows: number, cols: number): void { if (!rangeDopplerCanvas) return; const context = rangeDopplerCanvas.getContext('2d'); if (!context) return; const cellWidth = rangeDopplerCanvas.width / cols; const cellHeight = rangeDopplerCanvas.height / rows; context.lineWidth = 1.5; context.font = '11px "JetBrains Mono", monospace'; tracks.forEach((track) => { const x = (track.c + 0.5) * cellWidth; const y = (track.r + 0.5) * cellHeight; const coasting = track.misses > 0; context.strokeStyle = coasting ? 'rgba(232,192,122,0.35)' : 'rgba(232,192,122,0.6)'; context.beginPath(); track.trail.forEach(([row, col], index) => { const px = (col + 0.5) * cellWidth; const py = (row + 0.5) * cellHeight; if (index === 0) context.moveTo(px, py); else context.lineTo(px, py); }); context.stroke(); context.strokeStyle = coasting ? 'rgba(232,192,122,0.6)' : '#e8c07a'; context.beginPath(); context.arc(x, y, Math.max(5, cellWidth * 0.7), 0, Math.PI * 2); context.stroke(); context.fillStyle = '#e8c07a'; context.fillText(`T${String(track.id).padStart(2, '0')}`, x + 7, y - 7); }); }
function renderDetections(): void { if (!detectionList) return; const list = detectionList; empty(list); if (!tracksCache.length) { list.appendChild(h('div', { className: 'u-text-muted u-mono' }, 'sem alvos')); return; } tracksCache.forEach((track) => { const range = rangeMeters(track.r, { fftN: lastFrame?.rows ?? 64 }); const velocity = velocityMs(track.c, { dopplerN: lastFrame?.cols ?? 32 }); list.appendChild(h('div', { className: cx('rdr-det-row', track.misses > 0 && 'is-coasting') }, h('span', { className: 'rdr-det-row__id u-mono' }, `T${String(track.id).padStart(2, '0')}`), h('span', { className: 'rdr-det-row__range u-mono' }, `${range.toFixed(1)} m`), h('span', { className: 'rdr-det-row__vel u-mono' }, `${velocity >= 0 ? '+' : ''}${velocity.toFixed(1)} m/s`), h('span', { className: 'rdr-det-row__snr u-mono u-text-cyan' }, `${(20 * Math.log10(Math.max(track.snr, 1e-6))).toFixed(1)} dB`))); }); }
function cleanup(): void { source?.stop(); source = null; stopSatelliteMode(); tracker.reset(); tracksCache = []; previousMagnitude = null; lastFrame = null; }

export function radarPage(): HTMLDivElement { const page = h('div', { className: 'page-radar' }); page.append(buildHeader(), buildConsole(), buildSensorSources()); window.setTimeout(() => { void switchSource('mock'); }, 0); aoSair(page, cleanup); return page; }
