import '../styles/radio.css';
import { h, empty } from '../utils/helpers.js';
import { buildImmersiveHero } from '../utils/immersive';
import { storage } from '../core/storage.js';
import { toast } from '../utils/toast';
import { searchStations, COUNTRY_OPTIONS, GENRE_OPTIONS } from '../utils/radio-api.js';
import type { RadioStation } from '../utils/radio-api.js';

declare global { interface Window { webkitAudioContext?: typeof AudioContext } }

type RadioMode = 'synth' | 'online';
type SynthWave = OscillatorType;
type SynthStationKind = 'tom' | 'acorde' | 'morse' | 'sweep';
interface SynthStation { readonly freq: number; readonly nome: string; readonly tipo: SynthStationKind; readonly tom: number; readonly wave: SynthWave; readonly desc: string }
interface RadioQuery { name: string; country: string; tag: string }
interface RadioState { freq: number; volume: number; onlineVolume: number; mode: RadioMode; query: RadioQuery }
interface RadioView { readonly el: HTMLDivElement; stop(): void }
interface AudioNodes { readonly ctx: AudioContext; readonly noise: AudioBufferSourceNode; readonly noiseGain: GainNode; readonly osc: OscillatorNode; readonly sigGain: GainNode; readonly master: GainNode }
type NowPlayingPhase = 'idle' | 'loading' | 'playing' | 'error';

const STORAGE_KEY = 'radio:state';
const BAND_MIN = 87.5;
const BAND_MAX = 108;
const LOCK_RANGE = 0.35;
const STATIONS: readonly SynthStation[] = [
  { freq: 89.1, nome: 'Núcleo FM', tipo: 'tom', tom: 220, wave: 'sine', desc: 'Portadora grave do Núcleo Infinity.' },
  { freq: 92.4, nome: 'Rádio Alfa', tipo: 'acorde', tom: 330, wave: 'triangle', desc: 'Acorde de três tons da equipe ALFA.' },
  { freq: 95.7, nome: 'Sinal Morse OMEGA', tipo: 'morse', tom: 620, wave: 'sine', desc: 'Baliza repetindo "BALUARTE" em Morse.' },
  { freq: 98.9, nome: 'Onda Drift', tipo: 'sweep', tom: 440, wave: 'sawtooth', desc: 'Varredura contínua estilo Eurobeat.' },
  { freq: 101.5, nome: 'Estação Vanadis', tipo: 'tom', tom: 523, wave: 'sine', desc: 'Tom cristalino de referência.' },
  { freq: 104.3, nome: 'Frequência 11', tipo: 'acorde', tom: 174, wave: 'square', desc: 'Acorde sombrio do arco INDIA.' },
  { freq: 106.8, nome: 'Beacon Shadow', tipo: 'morse', tom: 760, wave: 'square', desc: 'Baliza cifrada de baixa potência.' },
];
const MORSE: Readonly<Record<string, string>> = { B: '-...', A: '.-', L: '.-..', U: '..-', R: '.-.', T: '-', E: '.' };
const MORSE_WORD = 'BALUARTE';
let routeWatcher: (() => void) | null = null;
let currentView: RadioView | null = null;

function isRecord(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === 'object' && !Array.isArray(value); }
function numberOr(value: unknown, fallback: number): number { return typeof value === 'number' && Number.isFinite(value) ? value : fallback; }
function stringOr(value: unknown, fallback: string): string { return typeof value === 'string' ? value : fallback; }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : 'erro desconhecido'; }
function loadState(): RadioState {
  const raw = storage.get<unknown>(STORAGE_KEY, null); const value = isRecord(raw) ? raw : {}; const queryValue = isRecord(value.query) ? value.query : {};
  const mode = value.mode === 'online' || value.mode === 'synth' ? value.mode : 'synth';
  return { freq: numberOr(value.freq, 95.7), volume: numberOr(value.volume, 0.6), onlineVolume: numberOr(value.onlineVolume, 0.7), mode, query: { name: stringOr(queryValue.name, ''), country: stringOr(queryValue.country, 'BR'), tag: stringOr(queryValue.tag, '') } };
}
function persist(state: RadioState): void { storage.set(STORAGE_KEY, state); }

export function radioPage(): HTMLDivElement {
  const state = loadState(); const fullPage = h('div', { className: 'page-radio' });
  fullPage.appendChild(buildImmersiveHero({ kicker: 'BALUARTE · MÍDIA · RÁDIO', title: 'Rádio', sub: 'SINTETIZADOR & ONLINE', desc: ['Dois modos: ', h('span', { className: 'u-text-cyan' }, 'Sintetizador'), ' — um receptor sintetizado via Web Audio, totalmente offline — e ', h('span', { className: 'u-text-cyan' }, 'Online'), ' — estações de rádio reais da internet via Radio Browser API. Rádio RF de verdade não funciona no navegador; o modo Online toca streams.'], hudLeft: '◉))) RÁDIO', hudRight: 'WEB AUDIO' }));
  const modeButtons: Record<RadioMode, HTMLButtonElement> = {} as Record<RadioMode, HTMLButtonElement>; const modeBar = h('div', { className: 'radio-mode' });
  (['synth', 'online'] as const).forEach((mode) => { const button = h('button', { className: 'radio-mode__btn', onclick: () => setMode(mode) }, mode === 'synth' ? '◉ Sintetizador' : '◈ Online'); modeButtons[mode] = button; modeBar.appendChild(button); }); fullPage.appendChild(modeBar);
  const content = h('div', { className: 'radio-content' }); fullPage.appendChild(content);
  function setMode(next: RadioMode): void { currentView?.stop(); state.mode = next; persist(state); (Object.entries(modeButtons) as Array<[RadioMode, HTMLButtonElement]>).forEach(([id, button]) => button.classList.toggle('is-active', id === next)); currentView = next === 'online' ? buildOnlineView(state) : buildSynthView(state); empty(content); content.appendChild(currentView.el); }
  if (routeWatcher) window.removeEventListener('hashchange', routeWatcher); routeWatcher = () => { if (!window.location.hash.startsWith('#/radio')) { currentView?.stop(); currentView = null; if (routeWatcher) window.removeEventListener('hashchange', routeWatcher); routeWatcher = null; } }; window.addEventListener('hashchange', routeWatcher); setMode(state.mode); return fullPage;
}

function buildSynthView(state: RadioState): RadioView {
  let power = false; let morseTimer: number | null = null; let animationFrame = 0; let audio: AudioNodes | null = null; const view = h('div', { className: 'radio-synth' });
  const frequencyDisplay = h('div', { className: 'radio-display__freq u-mono' }, state.freq.toFixed(1)); const stationName = h('div', { className: 'radio-display__station' }, '— estática —'); const signalBars = h('div', { className: 'radio-signal' }); for (let index = 0; index < 8; index += 1) signalBars.appendChild(h('span', { className: 'radio-signal__bar' }));
  function startAudio(): void { const Context = window.AudioContext ?? window.webkitAudioContext; if (!Context) { toast('Web Audio não está disponível neste navegador.', { type: 'warning' }); return; } const context = new Context(); const bufferSize = 2 * context.sampleRate; const buffer = context.createBuffer(1, bufferSize, context.sampleRate); const data = buffer.getChannelData(0); for (let index = 0; index < bufferSize; index += 1) data[index] = Math.random() * 2 - 1; const noise = context.createBufferSource(); noise.buffer = buffer; noise.loop = true; const noiseGain = context.createGain(); noiseGain.gain.value = 0; const oscillator = context.createOscillator(); oscillator.type = 'sine'; oscillator.frequency.value = 440; const signalGain = context.createGain(); signalGain.gain.value = 0; const master = context.createGain(); master.gain.value = state.volume; noise.connect(noiseGain); noiseGain.connect(master); oscillator.connect(signalGain); signalGain.connect(master); master.connect(context.destination); noise.start(); oscillator.start(); audio = { ctx: context, noise, noiseGain, osc: oscillator, sigGain: signalGain, master }; }
  function nearest(frequency: number): { station: SynthStation | null; proximity: number } { let best: SynthStation | null = null; let bestDistance = Infinity; STATIONS.forEach((station) => { const distance = Math.abs(station.freq - frequency); if (distance < bestDistance) { bestDistance = distance; best = station; } }); return { station: best, proximity: bestDistance <= LOCK_RANGE ? 1 - bestDistance / LOCK_RANGE : 0 }; }
  function clearMorse(): void { if (morseTimer !== null) { window.clearTimeout(morseTimer); morseTimer = null; } }
  function runMorse(): void { clearMorse(); if (!audio) return; const unit = 90; const sequence: Array<{ on: boolean; ms: number }> = []; for (const character of MORSE_WORD) { for (const symbol of MORSE[character] ?? '') { sequence.push({ on: true, ms: symbol === '-' ? unit * 3 : unit }); sequence.push({ on: false, ms: unit }); } sequence.push({ on: false, ms: unit * 2 }); } let index = 0; const step = (): void => { if (!audio || !power) return; const proximity = nearest(state.freq).proximity; const segment = sequence[index % sequence.length]; audio.sigGain.gain.setTargetAtTime(segment.on ? proximity * 0.5 : 0, audio.ctx.currentTime, 0.01); index += 1; morseTimer = window.setTimeout(step, segment.ms); }; step(); }
  function tune(): void { frequencyDisplay.textContent = state.freq.toFixed(1); const { station, proximity } = nearest(state.freq); const locked = proximity > 0; const lit = Math.round(proximity * 8); [...signalBars.children].forEach((bar, index) => bar.classList.toggle('is-lit', index < lit)); stationName.textContent = locked && power && station ? `▸ ${station.nome}` : power ? '— estática —' : 'desligado'; stationName.classList.toggle('is-locked', locked && power); if (!audio || !power) return; const now = audio.ctx.currentTime; audio.noiseGain.gain.setTargetAtTime((1 - proximity) * 0.16, now, 0.05); if (!station) { clearMorse(); audio.sigGain.gain.setTargetAtTime(0, now, 0.05); return; } audio.osc.type = station.wave; if (station.tipo === 'morse') { audio.osc.frequency.setTargetAtTime(station.tom, now, 0.02); if (morseTimer === null) runMorse(); return; } clearMorse(); audio.osc.frequency.setTargetAtTime(station.tipo === 'sweep' ? station.tom + Math.sin(now * 1.5) * 120 : station.tom, now, station.tipo === 'sweep' ? 0.05 : 0.03); audio.sigGain.gain.setTargetAtTime(proximity * 0.32, now, 0.04); }
  function loop(): void { if (power && audio && nearest(state.freq).station?.tipo === 'sweep') tune(); animationFrame = window.requestAnimationFrame(loop); }
  const powerButton = h('button', { className: 'btn btn--primary', onclick: () => { power = !power; if (power) { if (!audio) startAudio(); if (audio?.ctx.state === 'suspended') void audio.ctx.resume(); powerButton.textContent = '⏻ Desligar'; powerButton.classList.add('is-on'); if (!animationFrame) loop(); toast('Rádio ligado', { type: 'success' }); } else { powerButton.textContent = '⏻ Ligar'; powerButton.classList.remove('is-on'); clearMorse(); if (audio) { audio.noiseGain.gain.value = 0; audio.sigGain.gain.value = 0; } } tune(); } }, '⏻ Ligar');
  const dial = h('input', { className: 'radio-dial', type: 'range', 'aria-label': 'Sintonia — frequência em MHz', min: String(BAND_MIN), max: String(BAND_MAX), step: '0.1', value: String(state.freq), oninput: (event: Event) => { if (!(event.target instanceof HTMLInputElement)) return; state.freq = Number.parseFloat(event.target.value); persist(state); clearMorse(); tune(); } }); const volumeLabel = h('span', { className: 'u-mono u-text-cyan radio-vol__val' }, `${Math.round(state.volume * 100)}%`); const volumeSlider = h('input', { type: 'range', min: '0', max: '1', step: '0.05', value: String(state.volume), oninput: (event: Event) => { if (!(event.target instanceof HTMLInputElement)) return; state.volume = Number.parseFloat(event.target.value); volumeLabel.textContent = `${Math.round(state.volume * 100)}%`; persist(state); if (audio) audio.master.gain.setTargetAtTime(state.volume, audio.ctx.currentTime, 0.02); } });
  view.appendChild(h('div', { className: 'radio-set card' }, h('div', { className: 'radio-display' }, h('div', null, frequencyDisplay, h('span', { className: 'radio-display__unit' }, 'MHz')), stationName, signalBars), h('div', { className: 'radio-dial-wrap' }, h('span', { className: 'radio-dial__min' }, String(BAND_MIN)), dial, h('span', { className: 'radio-dial__max' }, String(BAND_MAX))), h('div', { className: 'radio-controls' }, powerButton, h('label', { className: 'radio-vol' }, h('span', null, 'Volume'), volumeSlider, volumeLabel)))); view.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, 'Estações Conhecidas'))); const stationList = h('div', { className: 'radio-stations' }); STATIONS.forEach((station) => stationList.appendChild(h('button', { className: 'radio-station', onclick: () => { state.freq = station.freq; dial.value = String(station.freq); persist(state); clearMorse(); tune(); if (!power) toast('Ligue o rádio para ouvir', { type: 'info' }); } }, h('span', { className: 'radio-station__freq u-mono' }, station.freq.toFixed(1)), h('span', { className: 'radio-station__body' }, h('span', { className: 'radio-station__nome' }, station.nome), h('span', { className: 'radio-station__desc' }, station.desc))))); view.appendChild(stationList); tune();
  return { el: view, stop: () => { clearMorse(); if (animationFrame) window.cancelAnimationFrame(animationFrame); animationFrame = 0; if (audio) { try { void audio.ctx.close(); } catch { /* já fechado */ } audio = null; } } };
}

function buildOnlineView(state: RadioState): RadioView {
  const view = h('div', { className: 'radio-online' }); const audio = new Audio(); audio.preload = 'none'; audio.volume = state.onlineVolume; let currentStation: RadioStation | null = null; const cards = new Map<string, HTMLButtonElement>();
  const nowPlayingIcon = h('span', { className: 'radio-np__icon' }, '◉'); const nowPlayingName = h('div', { className: 'radio-np__name' }, 'Nenhuma estação'); const nowPlayingMeta = h('div', { className: 'radio-np__meta u-mono' }, 'Busque e escolha uma estação abaixo'); const stopButton = h('button', { className: 'btn btn--sm', disabled: true, onclick: () => stopPlayback() }, '■ Parar'); const onlineVolumeValue = h('span', { className: 'u-mono u-text-cyan radio-vol__val' }, `${Math.round(state.onlineVolume * 100)}%`); const onlineVolume = h('input', { type: 'range', min: '0', max: '1', step: '0.05', value: String(state.onlineVolume), oninput: (event: Event) => { if (!(event.target instanceof HTMLInputElement)) return; state.onlineVolume = Number.parseFloat(event.target.value); audio.volume = state.onlineVolume; onlineVolumeValue.textContent = `${Math.round(state.onlineVolume * 100)}%`; persist(state); } });
  const nowPlaying = h('div', { className: 'radio-np card', dataset: { state: 'idle' } }, nowPlayingIcon, h('div', { className: 'radio-np__body' }, nowPlayingName, nowPlayingMeta), h('div', { className: 'radio-np__controls' }, stopButton, h('label', { className: 'radio-vol' }, h('span', null, 'Vol'), onlineVolume, onlineVolumeValue))); view.appendChild(nowPlaying);
  function setNowPlaying(phase: NowPlayingPhase, station: RadioStation | null, message = ''): void { nowPlaying.dataset.state = phase; nowPlayingIcon.textContent = { idle: '◉', loading: '◌', playing: '▶', error: '⚠' }[phase]; if (station) { nowPlayingName.textContent = station.name; const details = [station.country, station.codec, station.bitrate ? `${station.bitrate} kbps` : ''].filter(Boolean); nowPlayingMeta.textContent = message || details.join(' · ') || '—'; } else { nowPlayingName.textContent = 'Nenhuma estação'; nowPlayingMeta.textContent = message || 'Busque e escolha uma estação abaixo'; } stopButton.disabled = phase === 'idle'; }
  function highlight(uuid: string | null): void { cards.forEach((card, id) => card.classList.toggle('is-playing', id === uuid)); }
  function stopPlayback(): void { currentStation = null; audio.pause(); audio.removeAttribute('src'); audio.load(); highlight(null); setNowPlaying('idle', null); }
  function playStation(station: RadioStation): void { if (window.location.protocol === 'https:' && station.url.startsWith('http:')) { currentStation = station; highlight(station.uuid); setNowPlaying('error', station, 'Stream HTTP bloqueado pelo navegador (site em HTTPS)'); toast('Estação HTTP — bloqueada em site HTTPS', { type: 'warning' }); return; } currentStation = station; highlight(station.uuid); setNowPlaying('loading', station, 'Conectando…'); audio.src = station.url; const attempt = audio.play(); attempt.catch(() => { if (currentStation === station) setNowPlaying('error', station, 'Não foi possível tocar esta estação'); }); }
  audio.addEventListener('playing', () => { if (currentStation) setNowPlaying('playing', currentStation); }); audio.addEventListener('waiting', () => { if (currentStation) setNowPlaying('loading', currentStation, 'Carregando…'); }); audio.addEventListener('stalled', () => { if (currentStation) setNowPlaying('loading', currentStation, 'Sinal travado…'); }); audio.addEventListener('error', () => { if (currentStation) setNowPlaying('error', currentStation, 'Stream fora do ar ou indisponível'); });
  const nameInput = h('input', { className: 'input', type: 'search', placeholder: 'Nome da estação (opcional)…', value: state.query.name, onkeydown: (event: KeyboardEvent) => { if (event.key === 'Enter') void search(); } }); const countrySelect = h('select', { className: 'input' }, ...COUNTRY_OPTIONS.map((option) => h('option', { value: option.value, selected: option.value === state.query.country }, option.label))); const genreSelect = h('select', { className: 'input' }, ...GENRE_OPTIONS.map((option) => h('option', { value: option.value, selected: option.value === state.query.tag }, option.label))); const searchButton = h('button', { className: 'btn btn--primary', onclick: () => void search() }, 'Buscar');
  view.appendChild(h('div', { className: 'radio-search card' }, h('label', { className: 'radio-search__field' }, h('span', null, 'Nome'), nameInput), h('label', { className: 'radio-search__field' }, h('span', null, 'País'), countrySelect), h('label', { className: 'radio-search__field' }, h('span', null, 'Gênero'), genreSelect), searchButton)); view.appendChild(h('div', { className: 'section-header' }, h('h2', { className: 'section-header__title' }, 'Estações'))); const results = h('div', { className: 'radio-results' }); view.appendChild(results);
  function renderMessage(message: string, kind: 'error' | 'info' = 'info'): void { empty(results); cards.clear(); results.appendChild(h('div', { className: kind === 'error' ? 'radio-results__msg u-text-danger' : 'radio-results__msg u-text-muted' }, message)); }
  function renderResults(stations: readonly RadioStation[]): void { empty(results); cards.clear(); if (!stations.length) { renderMessage('Nenhuma estação encontrada. Tente outros filtros.'); return; } stations.forEach((station) => { const blocked = window.location.protocol === 'https:' && station.url.startsWith('http:'); const meta = [station.country, ...station.tags.slice(0, 3)].filter(Boolean).join(' · ') || 'sem gênero'; const card = h('button', { className: blocked ? 'radio-result is-http' : 'radio-result', title: blocked ? 'Stream HTTP — bloqueado em site HTTPS' : station.url, onclick: () => playStation(station) }, h('span', { className: 'radio-result__play' }, '▸'), h('span', { className: 'radio-result__body' }, h('span', { className: 'radio-result__name' }, station.name), h('span', { className: 'radio-result__meta u-mono' }, meta)), h('span', { className: 'radio-result__tag u-mono' }, blocked ? 'HTTP' : station.bitrate ? `${station.bitrate}k` : station.codec)); cards.set(station.uuid, card); results.appendChild(card); }); if (currentStation) highlight(currentStation.uuid); }
  let searching = false; async function search(): Promise<void> { if (searching) return; searching = true; searchButton.disabled = true; searchButton.textContent = 'Buscando…'; state.query = { name: nameInput.value.trim(), country: countrySelect.value, tag: genreSelect.value }; persist(state); renderMessage('Buscando estações…'); try { const stations = await searchStations({ name: state.query.name, countryCode: state.query.country, tag: state.query.tag, limit: 100 }); renderResults(stations); } catch (error: unknown) { renderMessage(`Falha ao buscar estações: ${errorMessage(error)}`, 'error'); toast('Erro ao buscar estações', { type: 'danger' }); } finally { searching = false; searchButton.disabled = false; searchButton.textContent = 'Buscar'; } }
  setNowPlaying('idle', null); void search(); return { el: view, stop: stopPlayback };
}
