// 30 temas — id + name + subtitle + swatches + attrs.
// Compartilhado entre o switcher (Baluarte Theme Switcher.html) e
// o canvas (Baluarte 30 Themes Canvas.html). Edite aqui pra os dois mudarem.

window.THEMES = [
  /* ── round 1 — escolhidos pra detalhar primeiro ── */
  { id: 'original',    name: 'Original',           group: 'Originais',
    subtitle: 'Cyan + magenta · ALL CAPS · glow · v1.0.0 ao vivo',
    swatches: ['#0a0e1a', '#00E5FF', '#FF2A8A'],
    attrs: { 'data-h1-gradient': 'on', 'data-radius': 'square' } },
  { id: 'calm',        name: 'Calm Material',      group: 'Originais',
    subtitle: 'Dark sóbrio · 1 accent cyan · sem ALL CAPS · confortável',
    swatches: ['#0F1419', '#3FB8DC', '#E6EDF3'],
    attrs: {} },
  { id: 'tron',        name: 'TRON',               group: 'Originais',
    subtitle: 'Preto absoluto · scanlines CRT · cyan glow · brackets',
    swatches: ['#020608', '#00F0FF', '#FF2A8A'],
    attrs: { 'data-scanlines': 'cyan', 'data-vignette': 'on', 'data-radius': 'square' } },
  { id: 'brutalist',   name: 'Brutalist Phosphor', group: 'Originais',
    subtitle: 'CRT verde · BBS 1992 · só monospace · zero gradient',
    swatches: ['#050a05', '#b6ff00', '#9bff9b'],
    attrs: { 'data-scanlines': 'green', 'data-logo-flat': 'on', 'data-radius': 'square' } },

  /* ── CRT vintage ── */
  { id: 'amber',       name: 'Amber CRT',          group: 'CRT vintage',
    subtitle: 'PDP-11 / IBM 3270 · phosphor âmbar · 100% monospace',
    swatches: ['#110800', '#ffd166', '#ffb454'],
    attrs: { 'data-scanlines': 'amber', 'data-vignette': 'on', 'data-logo-flat': 'on', 'data-radius': 'square' } },
  { id: 'matrix',      name: 'Matrix',             group: 'CRT vintage',
    subtitle: 'Preto absoluto · verde fosfórico · 100% mono · scanlines',
    swatches: ['#000000', '#00ff41', '#008f20'],
    attrs: { 'data-scanlines': 'matrix', 'data-vignette': 'on', 'data-logo-flat': 'on', 'data-radius': 'square' } },
  { id: 'pipboy',      name: 'Pip-Boy',            group: 'CRT vintage',
    subtitle: 'Fallout · verde RobCo · scanlines · 100% monospace',
    swatches: ['#001a04', '#4aff80', '#2fb058'],
    attrs: { 'data-scanlines': 'pipboy', 'data-vignette': 'on', 'data-logo-flat': 'on', 'data-radius': 'square' } },

  /* ── Editor de código ── */
  { id: 'dracula',     name: 'Dracula',            group: 'Editor de código',
    subtitle: 'Tema de editor clássico · roxo + pink + cinza azulado',
    swatches: ['#282a36', '#bd93f9', '#ff79c6'],
    attrs: { 'data-h1-gradient': 'on' } },
  { id: 'nord',        name: 'Nord',               group: 'Editor de código',
    subtitle: 'Polar night · azul gelo · contraste baixo · respiração',
    swatches: ['#2e3440', '#88c0d0', '#eceff4'],
    attrs: {} },
  { id: 'gruvbox',     name: 'Gruvbox',            group: 'Editor de código',
    subtitle: 'Marrom retrô + amarelo mostarda + laranja · warm dark',
    swatches: ['#282828', '#fabd2f', '#fe8019'],
    attrs: { 'data-h1-gradient': 'on' } },
  { id: 'tokyo',       name: 'Tokyo Night',        group: 'Editor de código',
    subtitle: 'Azul nocturno + lavanda · editor mais querido de 2024',
    swatches: ['#1a1b26', '#7aa2f7', '#bb9af7'],
    attrs: { 'data-h1-gradient': 'on' } },
  { id: 'solarized',   name: 'Solarized Dark',     group: 'Editor de código',
    subtitle: 'Ethan Schoonover · azul petróleo · paleta científica',
    swatches: ['#002b36', '#268bd2', '#fdf6e3'],
    attrs: {} },
  { id: 'github',      name: 'GitHub Dark',        group: 'Editor de código',
    subtitle: 'Dark mode oficial do GitHub · neutro · profissional',
    swatches: ['#0d1117', '#58a6ff', '#e6edf3'],
    attrs: {} },

  /* ── Retrofuturismo & neon ── */
  { id: 'synthwave',   name: 'Synthwave',          group: 'Retrofuturismo & neon',
    subtitle: 'Roxo + magenta + cyan · grid retrowave · ALL CAPS',
    swatches: ['#1a0b2e', '#ff4dd1', '#00f0ff'],
    attrs: { 'data-grid-bg': 'on', 'data-h1-gradient': 'on' } },
  { id: 'vaporwave',   name: 'Vaporwave',          group: 'Retrofuturismo & neon',
    subtitle: 'LIGHT · rosa + cyan · estética mall plaza · A E S T H E T I C',
    swatches: ['#f8d8ff', '#ff71ce', '#01cdfe'],
    attrs: { 'data-grid-bg': 'on', 'data-h1-gradient': 'on' } },
  { id: 'cyberpunk',   name: 'Cyberpunk 2077',     group: 'Retrofuturismo & neon',
    subtitle: 'Amarelo neon + cyan · ALL CAPS · zero radius · brutal',
    swatches: ['#0d0d0a', '#fcee0a', '#00ffe7'],
    attrs: { 'data-h1-gradient': 'on', 'data-radius': 'square' } },
  { id: 'y2k',         name: 'Y2K Chrome',         group: 'Retrofuturismo & neon',
    subtitle: 'LIGHT · cromado polido · 1999 software · radius generoso',
    swatches: ['#d8dde8', '#2858c8', '#b0b8d0'],
    attrs: { 'data-h1-gradient': 'on' } },
  { id: 'lcars',       name: 'LCARS',              group: 'Retrofuturismo & neon',
    subtitle: 'Star Trek TNG · pílulas gigantes · laranja + lilás · ALL CAPS',
    swatches: ['#000000', '#ff9966', '#cc99cc'],
    attrs: { 'data-h1-gradient': 'on' } },

  /* ── Tático, militar, industrial ── */
  { id: 'stealth',     name: 'Carbon Stealth',     group: 'Tático & industrial',
    subtitle: 'Matte black · vermelho sangue · F-117 · letterspacing brutal',
    swatches: ['#0a0a0a', '#d92638', '#e8e8e8'],
    attrs: { 'data-logo-flat': 'on', 'data-radius': 'square' } },
  { id: 'arctic',      name: 'Arctic Tactical',    group: 'Tático & industrial',
    subtitle: 'LIGHT · branco gelado · azul ártico · operações de inverno',
    swatches: ['#e8eef4', '#1c6dd0', '#122033'],
    attrs: {} },
  { id: 'blueprint',   name: 'Blueprint',          group: 'Tático & industrial',
    subtitle: 'Planta arquitetônica · azul cobalto + linhas brancas · grid',
    swatches: ['#0a3a6b', '#ffffff', '#80d8ff'],
    attrs: { 'data-grid-bg': 'on', 'data-logo-flat': 'on', 'data-radius': 'square' } },
  { id: 'hivis',       name: 'Hi-Vis Safety',      group: 'Tático & industrial',
    subtitle: 'Colete de obra · amarelo industrial sobre preto · choque',
    swatches: ['#0a0a0a', '#ffeb1e', '#ff7800'],
    attrs: { 'data-logo-flat': 'on', 'data-radius': 'square' } },

  /* ── Brand & mínimo ── */
  { id: 'vercel',      name: 'Vercel Mono',        group: 'Brand & mínimo',
    subtitle: 'Preto absoluto · branco puro · zero cor · brutalmente minimal',
    swatches: ['#000000', '#ffffff', '#a1a1a1'],
    attrs: { 'data-logo-flat': 'on' } },
  { id: 'hackernews',  name: 'Hacker News',        group: 'Brand & mínimo',
    subtitle: 'LIGHT · creme + laranja · Verdana · imutável desde 2007',
    swatches: ['#f6f6ef', '#ff6600', '#1a1a1a'],
    attrs: { 'data-logo-flat': 'on' } },
  { id: 'materialyou', name: 'Material You',       group: 'Brand & mínimo',
    subtitle: 'Android 13 dynamic · lilás suave + radius enorme · expressivo',
    swatches: ['#1d1b20', '#d0bcff', '#efb8c8'],
    attrs: { 'data-h1-gradient': 'on' } },

  /* ── Papel, manuscrito, arte ── */
  { id: 'solarpunk',   name: 'Solarpunk',          group: 'Papel & arte',
    subtitle: 'LIGHT · papel quente · sálvia + terracota · serif display',
    swatches: ['#f4ede0', '#5a7a3a', '#c46a3b'],
    attrs: { 'data-logo-flat': 'on' } },
  { id: 'newsprint',   name: 'Newsprint',          group: 'Papel & arte',
    subtitle: 'LIGHT · papel creme · tinta preta · serif slab · jornal',
    swatches: ['#f5f1e8', '#8a1810', '#1a1a14'],
    attrs: { 'data-logo-flat': 'on' } },
  { id: 'sepia',       name: 'Sepia Manuscript',   group: 'Papel & arte',
    subtitle: 'LIGHT · pergaminho + tinta marrom · serif clássico · sóbrio',
    swatches: ['#e8dcc0', '#8a1810', '#3a2410'],
    attrs: { 'data-logo-flat': 'on' } },
  { id: 'memphis',     name: 'Memphis 80s',        group: 'Papel & arte',
    subtitle: 'LIGHT · pink + cyan + amarelo · pós-modernismo italiano',
    swatches: ['#fff8e8', '#ff3d8b', '#00b8d4'],
    attrs: { 'data-h1-gradient': 'on' } },
  { id: 'mondrian',    name: 'Mondrian',           group: 'Papel & arte',
    subtitle: 'LIGHT · vermelho + azul + amarelo · grades pretas · De Stijl',
    swatches: ['#f5f3ec', '#dd1d20', '#0040b0'],
    attrs: { 'data-logo-flat': 'on' } },
];

window.THEMES_BY_ID = Object.fromEntries(window.THEMES.map((t) => [t.id, t]));
